/*
 * Son Frekans — kart destesi.
 * Her kart: { id, phase, hidden, image, speaker, text, glitchText, left, right }
 * image: karakter portresi dosya yolu (şimdilik SVG yer tutucu — gerçek fotoğraf gelince
 * aynı dosya adının üzerine yazmak yeterli, kod tarafında değişiklik gerekmez).
 * left/right: { label, effects, nextCardId, glitchLabel, scheduleCallback }
 * effects: {power,trust,sanity,signal} göstergeye eklenir (0-100 kelepçeli); effects.rel: {selin,serkan,military}
 * NPC/faksiyon güven skorlarına eklenir (game.js state.relationships, ayrıca 0-100 kelepçeli).
 * nextCardId varsa, o seçim yapıldığında deste havuzu yerine doğrudan o kart gelir (ANINDA dallanma).
 * scheduleCallback: { id, after, relKey?, variants? } — bu seçimden `after` kart SONRA (rastgele havuzun
 * önüne geçerek) devreye giren GECİKMELİ bir kart. Hedef kart `id` ile bulunur; relKey+variants verilirse
 * (variants: [{min, id}, ...], min'e göre azalan sırayla ilk eşleşen) devreye girdiği ANDAKİ
 * state.relationships[relKey] skoruna göre FARKLI bir kart gösterilir — aynı tetikleyiciden farklı ilişki
 * seviyelerinde farklı sonuçlar çıkar. O callback kartının KENDİ seçimlerine de yeni bir scheduleCallback
 * eklenerek A→B→C gibi çok adımlı zincirler kurulabilir (bkz. serkan_trust_test_A/_B/_final_*).
 * hidden:true olan kartlar rastgele havuzdan hiç çekilmez — sadece bir zincirin nextCardId/scheduleCallback'iyle ulaşılır.
 * glitchText / glitchLabel: Akıl <25 iken normal metnin/etiketin yerine gösterilen, elle yazılmış
 * bozulma varyantı (jenerik karakter-değiştirme yerine anlamlı bir çöküş sahnelemek için).
 * Yetişkin-only kadro: çocuk figürü yok.
 */

const STORY_META = {
  operatorName: "Ali Kayra",
  stationName: "Gözcü-7",
  frequency: "88.4 MHz",
};

const CAST = {
  ceylan: "Mühendis Ceylan Aksoy",
  serkan: "Serkan (Kaçak Asker)",
  fisilti: "88.4 MHz — Fısıltı",
  mert: "Mert (Eski Nöbetçi)",
  defne: "Buse (Korsan Telsizci)",
};

const DECK = [
  // ---- FAZ 1: Hayatta Kalma Rutini (Gün 1-5) ----
  {
    // TEST: İllüzyonun Kırılması — Elektrik Kesintisi & El Feneri. Kolay tetiklensin diye
    // faz 1 havuzunda ve hidden:false; denge/sıklık netleşince hidden:true + forcedNextId'ye
    // veya ayrı bir "rastgele nadir olay" mekanizmasına taşınabilir.
    id: "test_power_outage",
    phase: 1,
    type: "power_outage",
  },
  {
    id: "c1_shelter_call",
    phase: 1,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — bilinmeyen bir kadın",
    text: "“Kar fırtınası kesilmiyor. Sığınabileceğim bir yer söyler misin, ne olur?”",
    left: { label: "Cevap Verme", effects: { power: 0, trust: -10 } },
    right: { label: "Yönlendir", effects: { power: -6, trust: 15 } },
  },
  {
    id: "c1_filter_storm",
    phase: 1,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz Operatörü Demir (Sektör 4)",
    text: "“İstasyon! Fırtına sığınağın hava filtrelerini tıkadı. Temizlemek için 20 dakikalık bir durulma lazım. Radarınız ne diyor, çıkalım mı?”",
    left: { label: "Risk Almayın, Bekleyin", effects: { trust: -10, sanity: 5 } },
    right: { label: "Hemen Çıkın, Azalıyor", effects: { trust: 15, sanity: -10 } },
  },
  {
    id: "c1_generator_panel",
    phase: 1,
    image: "images/ceylan.jpg",
    speaker: CAST.ceylan,
    text: "“Ana türbin aşırı ısınıyor. Soğutma suyunu depodan çekebiliriz ama bu, içme suyu stoğunu bitirir.”",
    left: { label: "Suyu Jeneratöre Ver", effects: { power: 20, sanity: -10 } },
    right: { label: "Motoru Kıs, Rölantiye Al", effects: { power: -15, sanity: 5, signal: 5 } },
  },
  {
    id: "c1_scavenger_coords",
    phase: 1,
    image: "images/serkan.jpg",
    speaker: CAST.serkan,
    text: "“Elimde askeri piller var. Batı vadisindeki sığınağın koordinatını yayarsan ikisi de senin.”",
    left: { label: "Koordinatları Açıkla", effects: { power: 20, trust: -25, sanity: -15 } },
    right: { label: "Mikrofonu Kapat, Reddet", effects: { power: -10, trust: 10, sanity: 5 } },
  },
  {
    id: "c1_equipment_flicker",
    phase: 1,
    image: "images/ceylan.jpg",
    speaker: CAST.ceylan,
    text: "“Verici panelindeki ibre bir an tersine döndü, sonra kendi kendine düzeldi. Ben olsam bakardım.”",
    left: { label: "Görmezden Gel", effects: { power: -10 } },
    right: { label: "Sök, Bak", effects: { sanity: -6, power: 6 } },
  },
  {
    id: "c1_road_survivors",
    phase: 1,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — bir grup, uzaktan",
    text: "“Yoldayız, üç kişiyiz. Vadiden mi geçelim, tepeden mi — sen daha iyi görüyorsundur.”",
    left: { label: "Vadiden Git", effects: { trust: 8, power: -4 }, scheduleCallback: { id: "road_survivors_valley_result", after: 3 } },
    right: { label: "Tepeden Git", effects: { trust: -4, sanity: 4 }, scheduleCallback: { id: "road_survivors_hill_result", after: 3 } },
  },

  // ---- FAZ 2: Kırılma ve Çatallanma (Gün 6-12) ----
  {
    id: "c2_whisper_first_contact",
    phase: 2,
    image: "images/fisilti.jpg",
    speaker: CAST.fisilti,
    text: "“...nefesini duyabiliyorum... Anteni 14 derece doğuya çevirirsen, vadideki dizel tankerinin yerini söylerim...”",
    left: { label: "Frekansı Filtrele, Sustur", effects: { power: -5, sanity: 10, signal: -15 } },
    right: {
      label: "Anteni Doğuya Çevir",
      effects: { power: 15, sanity: -15, signal: 20 },
      nextCardId: "c2_voice_second_favor",
    },
  },
  {
    id: "c2_voice_second_favor",
    phase: 2,
    image: "images/fisilti.jpg",
    speaker: CAST.fisilti,
    text: "“Gördün mü, doğru söylemiştim. Bir kere daha güven bana — sana kimin geldiğini söyleyeyim.”",
    left: { label: "Hattı Kes", effects: { power: -5, sanity: 6, signal: -8 } },
    right: {
      label: "Dinlemeye Devam Et",
      effects: { signal: 16, trust: 8, sanity: -8 },
      nextCardId: "voice_antenna_2",
    },
  },
  {
    id: "c2_sky_flowing",
    phase: 2,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — panikli bir adam",
    text: "“Verdiğin koordinatta durdum. Gökyüzü... aşağı doğru akıyor. Yalan söylemiyorum.”",
    left: { label: "İnanma", effects: { trust: -10, sanity: 4 } },
    right: { label: "Ciddiye Al", effects: { sanity: -10, signal: 12 } },
  },
  {
    id: "c2_cult_caller",
    phase: 2,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — sakin bir dinleyici",
    text: "“Sesi biz de duyduk. Artık her akşam senin frekansına dönüp onu dinliyoruz. Kutsanmışsın.”",
    left: { label: "Sustur", effects: { trust: -14, sanity: 4 } },
    right: { label: "Yayına Devam Et", effects: { trust: 16, signal: 8 } },
  },
  {
    id: "c2_daughter_at_window",
    phase: 2,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — çökmüş bir baba sesi",
    text: "“Kızım hâlâ mutfak penceresinin önünde. Sabah oraya koydum, akşam hâlâ orada, aynı açıyla duruyor. Ona yemek götürdüm. Almadı. Sadece başını çevirdi, bana baktı ve... teşekkür eder gibi gülümsedi. Kimse bana bunun için teşekkür etmesin. Lütfen, biri onu bana geri getirsin.”",
    left: { label: "Onu zorla içeri al de", effects: { sanity: -10, trust: 6 } },
    right: { label: "Belki dinlenmek istiyordur, dokunma de", effects: { sanity: -6, trust: -8 } },
  },
  {
    id: "c2_fuel_crisis",
    phase: 2,
    image: "images/serkan.jpg",
    speaker: CAST.serkan,
    text: "“Son varilim bu. Fiyatı yükseldi — o 'sesi' bana bir kere duyur, yeter.”",
    left: { label: "Reddet", effects: { power: -16, sanity: 4 } },
    right: { label: "Kabul Et", effects: { power: 22, signal: 10, trust: -6 } },
  },
  {
    id: "c2_own_reflection",
    phase: 2,
    image: "images/station_cabin.jpg",
    speaker: "İstasyon — pencere camında",
    text: "Camda kendi yansımanı gördün. Bir saniye geç kaldı, sonra seninle aynı anda kırptı.",
    left: { label: "Camı Kapat", effects: { sanity: 8, power: -4 } },
    right: { label: "Bakmaya Devam Et", effects: { sanity: -12, signal: 8 } },
  },

  // ---- FAZ 3: Son Yayın (Gün 13+) ----
  {
    id: "c3_chief_tape",
    phase: 3,
    image: "images/archive_tape.jpg",
    speaker: "Eski İstasyon Şefinin Günlüğü",
    text: "Konsolun altında mühürlü bir kaset. Üzerinde el yazısı: “SON ÇARE: Frekansı tersine çevir.”",
    left: { label: "Kaseti Yak, İmha Et", effects: { sanity: 10, signal: -15 } },
    right: { label: "Çalara Yerleştir", effects: { power: -5, trust: -10, sanity: -20, signal: 25 } },
  },
  {
    id: "c3_shelter12_selin",
    phase: 3,
    image: "images/selin.jpg",
    speaker: "Sığınak-12 Lideri Selin",
    text: "“Kapımıza garip sesler çıkaran insanlar dayandı. Gözleri parlıyor, senin yayınındaki nakaratı mırıldanıyorlar. Açalım mı?”",
    left: { label: "Ateş Açın, Onlar İnsan Değil", effects: { trust: -15, sanity: -10, signal: 10 } },
    right: { label: "İçeri Alın, Donuyorlar", effects: { trust: -25, sanity: -15, signal: 20 } },
  },
  {
    id: "c3_voice_demand",
    phase: 3,
    image: "images/fisilti.jpg",
    speaker: CAST.fisilti,
    text: "“Vericiyi güçlendir. Sana ihtiyacım yok, sadece anteninin biraz daha büyümesine.”",
    left: { label: "Reddet", effects: { signal: -14, sanity: -6 } },
    right: { label: "Kabul Et", effects: { signal: 22, power: 10 } },
  },
  {
    id: "c3_mob_gathering",
    phase: 3,
    image: "images/station_cabin.jpg",
    speaker: "İstasyon — kapının dışından sesler",
    text: "Tepede ışıklar var. Kar üzerinde onlarca ayak izi, hepsi senin kapına doğru.",
    left: { label: "Kapıyı Kilitle", effects: { trust: -10, sanity: 6 } },
    right: { label: "İçeri Al", effects: { trust: 22, sanity: -10 } },
  },
  {
    id: "c3_static_between",
    phase: 3,
    image: "images/fisilti.jpg",
    speaker: "Statik — arada bir yerlerde",
    text: "Bazen artık hangi sesin sana ait olduğunu, hangisinin ondan geldiğini ayırt edemiyorsun.",
    left: { label: "Mikrofonu Kapat", effects: { power: -6, signal: -6 } },
    right: { label: "Konuşmaya Devam Et", effects: { sanity: -8, trust: 8 } },
  },
  {
    id: "c3_last_survivor",
    phase: 3,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — çok uzak, çok zayıf bir sinyal",
    text: "“Hâlâ biri var mı orada? Sadece bilmek istiyorum. Yalnız değilim demek için.”",
    left: { label: "Yayını Kes", effects: { power: 6, trust: -12 } },
    right: { label: "“Evet, Buradayım”", effects: { trust: 14, power: -8 } },
  },

  // ============================================================
  // ZİNCİR A — "Sığınak-12: Erzak Krizi" (Selin hattı, 4 adım)
  // ============================================================
  {
    id: "sel_supply_1",
    phase: 2,
    image: "images/selin.jpg",
    speaker: "Selin (Sığınak-12)",
    text: "“İstasyon, stoklar üç güne düştü. Kuzeydeki eski süpermarketin deposunu duydum ama oraya gitmek riskli — sen ne dersin?”",
    left: { label: "Gitmeyin, çok riskli", effects: { trust: -8, sanity: 4 } },
    right: {
      label: "Depoyu tarif et, gidin",
      effects: { trust: 10, power: -4 },
      nextCardId: "sel_supply_2",
    },
  },
  {
    id: "sel_supply_2",
    phase: 2,
    hidden: true,
    image: "images/selin.jpg",
    speaker: "Selin (Sığınak-12)",
    text: "“Depoyu bulduk ama boş değilmiş — başka bir grup çoktan yerleşmiş. Paylaşalım mı, yoksa bizimkiler öncelikli mi olsun?”",
    left: { label: "Sadece kendinize saklayın", effects: { trust: -12, sanity: -6, signal: 3 } },
    right: {
      label: "Paylaşın, yeter ki kimse ölmesin",
      effects: { trust: 14, power: -6 },
      nextCardId: "sel_supply_3",
    },
  },
  {
    id: "sel_supply_3",
    phase: 2,
    hidden: true,
    image: "images/selin.jpg",
    speaker: "Selin (Sığınak-12)",
    text: "“Paylaşım işe yaramadı. İki grup da aç kaldı, biri diğerinin payını çalmakla suçluyor. Birbirlerine silah doğrultmuşlar. Bana ne söylemem gerektiğini söyle, İSTASYON.”",
    glitchText: "“Payla%ım işe y&ramadı. İki gr&p da aç kaldı... sen de öylesin, değil mi? ?arışma. ?arışm—”",
    left: {
      label: "Eşit bölün, sakinleş deyin, sabredin",
      effects: { trust: 6, sanity: -4 },
      nextCardId: "sel_supply_4_good",
    },
    right: {
      label: "Güçlü olan hayatta kalır, buna karışma",
      effects: { trust: -10, sanity: 6, signal: 4 },
      glitchLabel: "G&çl& #lan h&yatta ka%ır, ?arışma",
      nextCardId: "sel_supply_4_bad",
    },
  },
  {
    id: "sel_supply_4_good",
    phase: 2,
    hidden: true,
    image: "images/selin.jpg",
    speaker: "Selin (Sığınak-12)",
    text: "“Ayakta kaldık. Sana borçluyuz.”",
    left: { label: "Rica ederim, dikkatli olun", effects: { trust: 8, sanity: 6 } },
    right: { label: "Bu son değil, hazırlıklı olun", effects: { trust: 4, sanity: 2 } },
  },
  {
    id: "sel_supply_4_bad",
    phase: 2,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — tanımadık biri, fısıltıyla",
    text: "“Selin'i bulamıyoruz. Kimse bulamıyor.”",
    glitchText: "“Selin'i bulamıyoruz. Kimse bulamıyor. Selin'i bulamıyoruz. Kimse bula%ıyor. S&lin'i b&lamıyo—”",
    left: { label: "Bağlantıyı kes", effects: { trust: -6, sanity: -4 } },
    right: { label: "Aramaya devam edin deyin", effects: { trust: -14, sanity: -10, signal: 6 } },
  },

  // ============================================================
  // ZİNCİR B — "Serkan'ın Kargosu" (4 adım)
  // ============================================================
  {
    id: "serkan_cargo_1",
    phase: 2,
    image: "images/serkan.jpg",
    speaker: CAST.serkan,
    text: "“Bir kontrol noktasının yakınında mühürlü bir askeri sandık buldum. Üzerinde hiçbir işaret yok. Açayım mı, yoksa körlemesine mi taşıyayım?”",
    left: { label: "Açma, tuzak olabilir", effects: { sanity: 6, trust: -4 } },
    right: {
      label: "Aç, ne olduğunu öğren",
      effects: { sanity: -6, signal: 6 },
      nextCardId: "serkan_cargo_2",
    },
  },
  {
    id: "serkan_cargo_2",
    phase: 2,
    hidden: true,
    image: "images/serkan.jpg",
    speaker: CAST.serkan,
    text: "“İçinde dosyalar var. 'Proje [karartılmış]' yazıyor, tarihi otuz yıl önce. Ve bir ses kaydı klasörü. İstasyon numaraları bizimkiyle aynı seride. Bunu yayınlayayım mı?”",
    left: { label: "Hayır, sakla, kimseye gösterme", effects: { trust: -6, signal: -8 } },
    right: {
      label: "Yayına ver, millet gerçeği bilsin",
      effects: { trust: 12, signal: 10 },
      nextCardId: "serkan_cargo_3",
    },
  },
  {
    id: "serkan_cargo_3",
    phase: 3,
    hidden: true,
    image: "images/serkan.jpg",
    speaker: CAST.serkan,
    text: "“Peşimdeler. Sandığı yok edip kaçayım mı, yoksa doğrudan sana, istasyona mı getireyim?”",
    left: { label: "Yok et, kendini kurtar", effects: { power: 4, trust: -6 } },
    right: {
      label: "Bana getir, burada saklarız",
      effects: { power: -8, trust: 8, signal: 12 },
      nextCardId: "serkan_cargo_4",
    },
  },
  {
    id: "serkan_cargo_4",
    phase: 3,
    hidden: true,
    image: "images/archive_tape.jpg",
    speaker: "İstasyon — kasetçalar",
    text: "Serkan sandığı ulaştırdı. İçindeki ses kaydını dinliyorsun: otuz yıl önceki bir operatörün sesi, kelimesi kelimesine senin son üç gündür söylediğin cümleleri söylüyor. Kayıt senin adını bilmiyor — ama “Gözcü-7'deki sen” diyor.",
    glitchText: "...G&zc&-7'deki s?n. G&zc&-7'deki s?n. G&z%ü-7'd&ki... Gözcü-7'd&ki s&n.",
    left: { label: "Kaydı sil, unutmaya çalış", effects: { sanity: 8, signal: -6 } },
    right: { label: "Kaydı sakla, tekrar dinle", effects: { sanity: -14, signal: 8 } },
  },

  // ============================================================
  // ZİNCİR C — "Antene Sızma" (c2_whisper_first_contact →
  // c2_voice_second_favor zincirinin doğal devamı, 3 yeni adım)
  // ============================================================
  {
    id: "voice_antenna_2",
    phase: 3,
    hidden: true,
    image: "images/fisilti.jpg",
    speaker: CAST.fisilti,
    text: "“Bana bir kez daha güvendin, teşekkür ederim. Şimdi küçük bir şey daha — vericinin yanında bulacağın bir bobin var. Onu takarsan, sana çok daha net duyabileceğim.”",
    left: { label: "Hayır, bu kadarı yeter", effects: { signal: -10, sanity: 5 } },
    right: {
      label: "Tak, dene",
      effects: { signal: 14, sanity: -8 },
      nextCardId: "voice_antenna_3",
    },
  },
  {
    id: "voice_antenna_3",
    phase: 3,
    hidden: true,
    image: "images/fisilti.jpg",
    speaker: CAST.fisilti,
    text: "“Bunu duyman normal, alışacaksın. Şimdi mikrofonu aç ve söylediğimi tekrarla — sadece rezonansı test ediyoruz.”",
    left: {
      label: "Hayır, tekrarlamıyorum",
      effects: { signal: -6, sanity: 4 },
      glitchLabel: "?m&yıml&trarkeT ,rıyaH",
    },
    right: {
      label: "Cümleyi tekrarla",
      effects: { signal: 16, sanity: -10 },
      nextCardId: "voice_antenna_4",
    },
  },
  {
    id: "voice_antenna_4",
    phase: 3,
    hidden: true,
    image: "images/fisilti.jpg",
    speaker: CAST.fisilti,
    text: "“Görüyorsun, ikimiz de aynı şeyi istiyoruz — duyulmak. Son bir şey kaldı: fırtınada kuleye çık, anteni elinle ayarla. Sana yol göstereceğim, düşmeyeceksin.”",
    left: { label: "Hayır. Bobini söküyorum", effects: { signal: -20, power: -8 } },
    right: { label: "Kuleye çık", effects: { signal: 25, sanity: -12, power: 6 } },
  },

  // ============================================================
  // İÇERİK PAKETİ 2 — Faz 1 genişlemesi (24 yeni kart)
  // ============================================================
  {
    id: "frozen_river",
    phase: 1,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — bilinmeyen bir adam",
    text: "“Nehri geçmem lazım ama buz ne kadar sağlam bilmiyorum. Sen görebiliyor musun oradan?”",
    left: { label: "Geçme, riskli", effects: { trust: -6, sanity: 4 }, scheduleCallback: { id: "river_avoided_result", after: 3 } },
    right: { label: "Kenardan, yavaş geç", effects: { trust: 10, power: -3 }, scheduleCallback: { id: "river_crossed_result", after: 3 } },
  },
  {
    id: "medicine_split",
    phase: 1,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — bir grup, hasta biriyle",
    text: "“Elimizdeki tek ilaç bu. En hasta olana mı verelim, yoksa herkese eşit mi bölelim?”",
    left: { label: "En hastaya ver, tümünü", effects: { trust: 8, sanity: -4 }, scheduleCallback: { id: "medicine_focused_result", after: 3 } },
    right: { label: "Eşit bölün, kimse tam iyileşmez", effects: { trust: -4, sanity: 6 }, scheduleCallback: { id: "medicine_shared_result", after: 3 } },
  },
  {
    id: "dog_howling",
    phase: 1,
    image: "images/station_cabin.jpg",
    speaker: "İstasyon — dışarıda",
    text: "Saatlerdir bir köpek uluyor, hiç durmuyor. Çıkıp bakmak mı, mikrofonu açık bırakıp beklemek mi?",
    left: { label: "İçeride kal, görmezden gel", effects: { sanity: 4 } },
    right: { label: "Çıkıp bak", effects: { power: -4, sanity: -6 } },
  },
  {
    id: "map_trade",
    phase: 1,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — bir kadın, tüccar",
    text: "“Elimde eski bir bölge haritası var. Mazotunla takas eder misin?”",
    left: { label: "Hayır, mazot değerli", effects: { power: 4, trust: -4 } },
    right: { label: "Takas et", effects: { power: -10, trust: 6 } },
  },
  {
    id: "broken_antenna_report",
    phase: 1,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — sakin bir ses",
    text: "“Sinyalin son iki gündür kesik kesik geliyor. Fark ettin mi?”",
    left: { label: "Fark etmedim, önemli değil", effects: { sanity: -4 } },
    right: { label: "Anteni kontrol edeceğim", effects: { power: -6, sanity: 4 } },
  },
  {
    id: "convoy_warning",
    phase: 1,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — bir konvoy lideri",
    text: "“Bölgenden geçeceğiz. Güvenli yol hangisi, tehlikeli olan hangisi?”",
    left: { label: "Bilmiyorum de, karışma", effects: { trust: -8 }, scheduleCallback: { id: "convoy_unknown_result", after: 3 } },
    right: { label: "Bildiğin doğru yolu göster", effects: { trust: 14, power: -4 }, scheduleCallback: { id: "convoy_guided_result", after: 3 } },
  },
  {
    id: "night_knock",
    phase: 1,
    image: "images/station_cabin.jpg",
    speaker: "İstasyon — kapıda",
    text: "Gece yarısı kapıda hafif bir tıklama sesi. Sonra sessizlik.",
    left: { label: "Kapıyı açma", effects: { sanity: 6 } },
    right: { label: "Kim var diye seslen", effects: { sanity: -8, signal: 4 } },
  },
  {
    id: "ceylan_spare_parts",
    phase: 1,
    image: "images/ceylan.jpg",
    speaker: CAST.ceylan,
    text: "“Yedek parçalarım tükeniyor. Terk edilmiş bir istasyondan söküp getirebilirim ama tehlikeli bölge.”",
    left: { label: "Gitme, riske değmez", effects: { power: -6, trust: 4 } },
    right: { label: "Git, getir", effects: { power: 10, sanity: -4 } },
  },
  {
    id: "serkan_trade_offer",
    phase: 1,
    image: "images/serkan.jpg",
    speaker: CAST.serkan,
    text: "“Elimde birkaç konserve var. Karşılığında bana yakındaki devriyelerin saatini söyle.”",
    left: { label: "Reddet", effects: { power: -4, trust: 4 } },
    right: { label: "Bilgiyi ver, konserveleri al", effects: { power: 8, trust: -8 } },
  },
  {
    id: "weather_report_request",
    phase: 1,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — bir çiftçi",
    text: "“Yarın hava nasıl olacak dersin? Hayvanları dışarı çıkarayım mı?”",
    left: { label: "Bilmiyorum, riske girme de", effects: { trust: -4, sanity: 4 }, scheduleCallback: { id: "weather_silent_result", after: 3 } },
    right: { label: "Tahminimi paylaş", effects: { trust: 8, sanity: -4 }, scheduleCallback: { id: "weather_shared_result", after: 3 } },
  },
  {
    id: "solar_panel_theft",
    phase: 1,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — telaşlı bir ses",
    text: "“Birileri güneş panelimizi sökmeye çalışıyor! Ne yapmalıyız?”",
    left: { label: "Görmezden gel, karışma", effects: { trust: -10 }, scheduleCallback: { id: "panel_stolen_result", after: 3 } },
    right: { label: "Karşı çıkın, bağırın", effects: { trust: 10, sanity: -4 }, scheduleCallback: { id: "panel_defended_result", after: 3 } },
  },
  {
    id: "frostbite_caller",
    phase: 1,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — acı içinde bir ses",
    text: "“Ayak parmaklarım morardı. Ne yapmalıyım, bilgin var mı?”",
    left: { label: "Beklet, bilmiyorum", effects: { trust: -6 }, scheduleCallback: { id: "frostbite_untreated_result", after: 3 } },
    right: { label: "Elimden geleni anlat", effects: { trust: 8, sanity: -4 }, scheduleCallback: { id: "frostbite_treated_result", after: 3 } },
  },
  {
    id: "lost_dog",
    phase: 1,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — bir kadın",
    text: "“Köpeğim kayboldu, fırtınadan önce kaçtı. Görme ihtimalin var mı?”",
    left: { label: "Görmedim, üzgünüm", effects: { sanity: 2 }, scheduleCallback: { id: "dog_not_found_result", after: 4 } },
    right: { label: "Bulursam haber veririm, sen de ara", effects: { trust: 6, sanity: 2 }, scheduleCallback: { id: "dog_found_result", after: 4 } },
  },
  {
    id: "fuel_leak",
    phase: 1,
    image: "images/ceylan.jpg",
    speaker: CAST.ceylan,
    text: "“Yakıt deposunda küçük bir sızıntı var. Hemen mi tamir edelim, yoksa gündüz bekleyelim mi?”",
    left: { label: "Şimdi tamir et, karanlıkta riskli olsa da", effects: { power: -8, sanity: -4 } },
    right: { label: "Sabahı bekle", effects: { power: -12 } },
  },
  {
    id: "signal_relay_request",
    phase: 1,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — uzak bir grup",
    text: "“Sinyalini bizim bölgeye kadar güçlendirebilir misin? Daha çok insana ulaşırız ama bizi de bilinir kılar.”",
    left: { label: "Hayır, riskli", effects: { trust: -6, signal: -4 } },
    right: { label: "Yap, deneyelim", effects: { trust: 10, signal: 8 } },
  },
  {
    id: "trader_caravan",
    phase: 1,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — gezici bir tüccar",
    text: "“Kervanla geçiyoruz. Bize güvenli bir durak önerir misin?”",
    left: { label: "Önerme, tanımıyorum sizi", effects: { trust: -4 }, scheduleCallback: { id: "caravan_unguided_result", after: 3 } },
    right: { label: "Öner", effects: { trust: 8, power: -2 }, scheduleCallback: { id: "caravan_guided_result", after: 3 } },
  },
  {
    id: "battery_ration",
    phase: 1,
    image: "images/ceylan.jpg",
    speaker: CAST.ceylan,
    text: "“Pilleri tam güçte kullanıyoruz. Tasarrufa geçelim mi, yoksa riske girip devam mı edelim?”",
    left: { label: "Tasarrufa geç", effects: { power: 6, trust: -2 } },
    right: { label: "Tam güç devam", effects: { power: -8, trust: 4 } },
  },
  {
    id: "static_burst",
    phase: 1,
    image: "images/station_cabin.jpg",
    speaker: "İstasyon — konsol",
    text: "Aniden kısa, keskin bir statik patlaması oldu. Sonra her şey normale döndü.",
    left: { label: "Not al, geç", effects: { sanity: 2 } },
    right: { label: "Kaynağını ara", effects: { sanity: -4, signal: 6 } },
  },
  {
    id: "serkan_check_in",
    phase: 1,
    image: "images/serkan.jpg",
    speaker: CAST.serkan,
    text: "“Sadece kontrol ediyorum, hâlâ hayattasın değil mi? Bugün sakin geçti benim için.”",
    left: { label: "Kısaca cevap ver", effects: { trust: 4 } },
    right: { label: "Sohbet et, biraz açıl", effects: { trust: 8, sanity: -2 } },
  },
  {
    id: "abandoned_vehicle",
    phase: 1,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — bir yolcu",
    text: "“Yolda terk edilmiş bir araç buldum, içinde erzak olabilir. Karıştırayım mı?”",
    left: { label: "Karıştırma, tuzak olabilir", effects: { sanity: 4 } },
    right: { label: "Karıştır", effects: { power: 6, sanity: -4 } },
  },
  {
    id: "shared_radio_frequency",
    phase: 1,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — komşu bir istasyon operatörü",
    text: "“Frekansını paylaşır mısın? Nöbetleşe yayın yapabiliriz, ikimiz de dinlenebiliriz.”",
    left: { label: "Hayır, kendi başımayım", effects: { trust: -4 } },
    right: { label: "Paylaş, birlikte yayın yapalım", effects: { trust: 10, power: -4 } },
  },
  {
    id: "ice_storm_shelter",
    phase: 1,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — bir aile",
    text: "“Buz fırtınası bizi yakaladı, en yakın sığınak neresi?”",
    left: { label: "En yakın olanı söyle, riskli olsa da", effects: { trust: 10, power: -4 }, scheduleCallback: { id: "shelter_near_result", after: 3 } },
    right: { label: "Güvenli ama uzak olanı söyle", effects: { trust: 4, power: -8 }, scheduleCallback: { id: "shelter_far_result", after: 3 } },
  },
  {
    id: "old_radio_manual",
    phase: 1,
    image: "images/archive_tape.jpg",
    speaker: "İstasyon — raf",
    text: "Tozlu bir kılavuzda vericiyle ilgili eski bir not buluyorsun: “Gece yayın yapma, dinliyor.”",
    left: { label: "Notu yırt, boş ver", effects: { sanity: 4 } },
    right: { label: "Notu sakla, dikkate al", effects: { sanity: -4, signal: 2 } },
  },
  {
    id: "serkan_ammo_trade",
    phase: 1,
    image: "images/serkan.jpg",
    speaker: CAST.serkan,
    text: "“Cephanem fazla geldi, birazını istasyona bırakabilirim. Karşılığında bir şey istemiyorum bu sefer.”",
    left: { label: "Kabul etme, şüpheli", effects: { trust: 2 } },
    right: { label: "Kabul et, teşekkür et", effects: { power: 6, trust: 6 } },
  },

  // ============================================================
  // İÇERİK PAKETİ 2 — Faz 2 genişlemesi (21 yeni kart + Zincir D)
  // ============================================================
  {
    id: "two_frequencies",
    phase: 2,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — şaşkın bir dinleyici",
    text: "“Bazen aynı anda iki ayrı sesini duyuyoruz, ikisi de senin gibi konuşuyor. Fark ettin mi?”",
    left: { label: "Hayır, tek yayın yapıyorum, yanılıyorsunuz", effects: { trust: -6, sanity: -4 } },
    right: { label: "Garip, ben de bir şey fark ettim", effects: { sanity: -8, signal: 8 } },
  },
  {
    id: "shelter_dispute",
    phase: 2,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — iki grup birden",
    text: "“Sınırımız konusunda anlaşamıyoruz, sen karar ver: kim nerede kalacak?”",
    left: { label: "İlk gelen kalsın", effects: { trust: -6 }, scheduleCallback: { id: "dispute_unfair_result", after: 3 } },
    right: { label: "Ortadan bölün", effects: { trust: 8, sanity: -4 }, scheduleCallback: { id: "dispute_fair_result", after: 3 } },
  },
  {
    id: "ceylan_warns_pattern",
    phase: 2,
    image: "images/ceylan.jpg",
    speaker: CAST.ceylan,
    text: "“Sinyaldeki o ‘rastgele’ parazitler aslında bir düzen izliyor. Bu beni endişelendiriyor.”",
    left: { label: "Önemseme, tesadüf", effects: { sanity: 4, signal: -4 } },
    right: { label: "Haklısın, ben de fark ettim", effects: { sanity: -6, signal: 6 } },
  },
  {
    id: "serkan_second_thoughts",
    phase: 2,
    image: "images/serkan.jpg",
    speaker: CAST.serkan,
    text: "“Sattığım o koordinatlar yüzünden bir grup zarar gördü galiba. Bilmiyorum ne yapacağımı.”",
    left: { label: "Unut, hayatta kalmak önemli", effects: { trust: -4, sanity: 4 } },
    right: { label: "Telafi et, bir şey yap", effects: { trust: 8, power: -6 } },
  },
  {
    id: "shared_delusion",
    phase: 2,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — bir kadın, tedirgin",
    text: "“Sesin söylediklerini rüyamda görüyorum, tıpa tıp aynı kelimelerle. Bu normal mi?”",
    left: { label: "Tesadüf, endişelenme", effects: { trust: 4 } },
    right: { label: "Bende de oluyor, korkuyorum", effects: { sanity: -8, signal: 6 } },
  },
  {
    id: "voice_silence_test",
    phase: 2,
    image: "images/fisilti.jpg",
    speaker: CAST.fisilti,
    text: "“Bu akşam yayın yapma. Sadece dinle. Göreceksin, daha iyi anlaşacağız.”",
    left: { label: "Yayını her zamanki gibi yap", effects: { signal: -8, sanity: 4 } },
    right: { label: "Sessiz kal, dinle", effects: { signal: 10, trust: -6 } },
  },
  {
    id: "frequency_cartographer",
    phase: 2,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — meraklı bir adam",
    text: "“Bütün garip sinyalleri bir haritaya işliyorum. Senin frekansını da ekleyebilir miyim?”",
    left: { label: "Hayır, ekleme", effects: { signal: -4, trust: -2 } },
    right: { label: "Ekle, belki işe yarar", effects: { signal: 6, trust: 4 } },
  },
  {
    id: "selin_illness_report",
    phase: 2,
    image: "images/selin.jpg",
    speaker: "Selin (Sığınak-12)",
    text: "“Sığınakta bir hastalık yayılıyor, kaynağını bilmiyoruz. Karantina mı, yoksa herkesi bir arada mı tutalım?”",
    left: { label: "Karantinaya alın", effects: { trust: 6, sanity: -4 } },
    right: { label: "Bir arada kalın, moral önemli", effects: { trust: -8, sanity: 4 } },
  },
  {
    id: "traveling_preacher",
    phase: 2,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — gezgin bir vaiz",
    text: "“Senin sesin bize bir işaret gönderiyor diyorum cemaatime. Buna izin veriyor musun?”",
    left: { label: "Hayır, bu bir yanılgı, durdur onları", effects: { trust: -10, signal: -6 } },
    right: { label: "Engelleme, inansınlar", effects: { trust: 8, signal: 8 } },
  },
  {
    id: "equipment_sabotage",
    phase: 2,
    image: "images/station_cabin.jpg",
    speaker: "İstasyon — konsol",
    text: "Ana kabloda kesik izleri var. Biri mi yoksa fare mi, bilmiyorsun.",
    left: { label: "Görmezden gel, tamir et", effects: { power: -6 } },
    right: { label: "Kim yaptı araştır", effects: { sanity: -6, power: -4 } },
  },
  {
    id: "shared_nightmare",
    phase: 2,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — üç ayrı dinleyici",
    text: "Üç farklı kişi aynı anda arayıp aynı kabusu anlattı: senin sesini kaybettiğin bir rüya.",
    left: { label: "Tesadüf, kapat telefonu", effects: { sanity: 4 } },
    right: { label: "Detayları dinle", effects: { sanity: -10, signal: 8 } },
  },
  {
    id: "own_voice_recording",
    phase: 2,
    image: "images/archive_tape.jpg",
    speaker: "İstasyon — kayıt cihazı",
    text: "Kendi sesini kaydedip geri dinliyorsun. Söylemediğin bir kelime, tam ortada, senin sesinle.",
    glitchText: "K&ndi ses%ni ka%dedip g&ri dinliyor#un. S&ylemediğin... s&ylemediğin bir kel%me... s&ylemediğin—",
    left: { label: "Kaydı sil", effects: { sanity: 6, signal: -6 } },
    right: { label: "Tekrar dinle, emin ol", effects: { sanity: -10, signal: 8 } },
  },
  {
    id: "serkan_double_deal",
    phase: 2,
    image: "images/serkan.jpg",
    speaker: CAST.serkan,
    text: "“İtiraf etmeliyim, başka bir istasyona da aynı bilgiyi sattım. Kızma, hayatta kalmam gerekiyordu.”",
    left: { label: "Güvenini kaybet, sınırla onu", effects: { trust: -4 } },
    right: { label: "Anla, affet", effects: { trust: 10, sanity: -2 } },
  },
  {
    id: "quiet_hour_request",
    phase: 2,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — bir grup",
    text: "“Her gece belli bir saatte tamamen sessiz kalmanı istiyoruz, sanki bir şey o saatte dinliyor.”",
    left: { label: "Hayır, yayına devam ederim", effects: { signal: -4, trust: -4 } },
    right: { label: "Kabul et, sessiz kal", effects: { signal: 6, trust: 6 } },
  },
  {
    id: "ceylan_personal_history",
    phase: 2,
    image: "images/ceylan.jpg",
    speaker: CAST.ceylan,
    text: "“Sana hiç anlatmadım ama ben de bir zamanlar bir istasyonu terk ettim. Bu yüzden buradayım.”",
    left: { label: "Detay isteme, saygı duy", effects: { trust: 4 } },
    right: { label: "Daha fazlasını sor", effects: { trust: 8, sanity: -2 } },
  },
  {
    id: "fake_rescue_broadcast",
    phase: 2,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — tanımadık bir ses",
    text: "“Ben askeri kurtarma ekibiyim, koordinatını ver, seni almaya geliyoruz.”",
    left: { label: "Verme, güvenmiyorum", effects: { trust: -4, sanity: 4, rel: { military: -5 } }, scheduleCallback: { id: "rescue_refused_result", after: 3 } },
    right: { label: "Koordinatı ver", effects: { trust: 6, signal: 6, rel: { military: 5 } }, scheduleCallback: { id: "rescue_trap_result", after: 3 } },
  },
  {
    id: "selin_trust_test",
    phase: 2,
    image: "images/selin.jpg",
    speaker: "Selin (Sığınak-12)",
    text: "“Bir şey soracağım ve dürüst cevap istiyorum: sen hâlâ sen misin?”",
    left: { label: "Evet, hâlâ benim", effects: { trust: 8, sanity: -4, rel: { selin: 8 } } },
    right: { label: "Bilmiyorum artık", effects: { trust: -6, sanity: 6, rel: { selin: -8 } } },
  },
  {
    id: "long_range_contact",
    phase: 2,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — çok uzak bir bölgeden",
    text: "“Yüzlerce kilometre öteden arıyorum, sinyalin buraya kadar ulaşıyor. Bu mümkün mü?”",
    left: { label: "İmkansız, yanlış numarasın", effects: { signal: -4 } },
    right: { label: "İnanılmaz, konuşalım", effects: { signal: 8, trust: 4 } },
  },
  {
    id: "serkan_wound",
    phase: 2,
    image: "images/serkan.jpg",
    speaker: CAST.serkan,
    text: "“Yaralandım, ciddi değil ama kanama var. Ne yapmalıyım, bilgin var mı?”",
    left: { label: "Sıkıca sar, dinlen de", effects: { trust: 6, sanity: -2 } },
    right: { label: "Kendi başınasın, idare et", effects: { trust: -6 } },
  },
  {
    id: "midnight_choir",
    phase: 2,
    image: "images/fisilti.jpg",
    speaker: "Telsiz — birden fazla ses, koro gibi",
    text: "Aynı anda konuşan onlarca ses duyuyorsun, hepsi aynı cümleyi tekrarlıyor: “seni duyuyoruz.”",
    glitchText: "‘s&ni duy#yoruz’ ‘s&ni duy#yoruz’ ‘s&ni d%y#yoruz’ ‘s&ni...’",
    left: { label: "Frekansı kapat", effects: { power: -4, signal: -8 } },
    right: { label: "Dinlemeye devam et", effects: { sanity: -10, signal: 10 } },
  },
  {
    id: "ceylan_leaving_thought",
    phase: 2,
    image: "images/ceylan.jpg",
    speaker: CAST.ceylan,
    text: "“Bazen buradan gitmeyi düşünüyorum. Sen kalır mısın, ben gitsem?”",
    left: { label: "Git, anlıyorum", effects: { trust: -6, sanity: 4 } },
    right: { label: "Kalmanı istiyorum", effects: { trust: 10, sanity: -2 } },
  },
  {
    id: "twin_signal_1",
    phase: 2,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — birden fazla dinleyici",
    text: "“Başka bir istasyon duyduk, kendine ‘Gözcü-3’ diyor. Sizinkiyle aynı formatta yayın yapıyor.”",
    left: { label: "Önemseme, tesadüf olabilir", effects: { signal: -4 } },
    right: {
      label: "Onu bulmaya çalış",
      effects: { signal: 6, sanity: -4 },
      nextCardId: "twin_signal_2",
    },
  },
  {
    id: "twin_signal_2",
    phase: 2,
    hidden: true,
    image: "images/fisilti.jpg",
    speaker: "Gözcü-3 — bilinmeyen operatör",
    text: "“Sen de mi hâlâ oradasın? Ben buradan çıkamıyorum. Sen çıkabildin mi?” diyor tanımadığın bir ses.",
    left: { label: "Bağlantıyı kes, cevap verme", effects: { sanity: 4, signal: -8 } },
    right: {
      label: "“Hayır, ben de çıkamıyorum” de",
      effects: { sanity: -10, signal: 12 },
      nextCardId: "twin_signal_3",
    },
  },

  // ============================================================
  // İÇERİK PAKETİ 2 — Faz 3 genişlemesi (22 yeni kart + Zincir D finali)
  // ============================================================
  {
    id: "last_broadcast_request",
    phase: 3,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — bir grup dinleyici",
    text: "“Belki son gecendir, belki değil. Bize son bir şey söyler misin, kaydetmek istiyoruz.”",
    left: { label: "Hayır, henüz bitmedi bu", effects: { sanity: 4, trust: -4 } },
    right: { label: "Son sözlerini söyle", effects: { sanity: -8, trust: 10 } },
  },
  {
    id: "serkan_final_choice",
    phase: 3,
    image: "images/serkan.jpg",
    speaker: CAST.serkan,
    text: "“Kalıp savaşayım mı, yoksa şimdi kaçayım mı? Sana soruyorum çünkü başka kimsem yok.”",
    left: { label: "Kaç, kendini kurtar", effects: { trust: -6, sanity: 4 } },
    right: { label: "Kal, birlikte direnelim", effects: { trust: 10, power: -6 } },
  },
  {
    id: "ceylan_last_repair",
    phase: 3,
    image: "images/ceylan.jpg",
    speaker: CAST.ceylan,
    text: "“Vericiyi tamamen yeniden kurabilirim ama jeneratörü tamamen durdurmam gerek, birkaç saat karanlıkta kalırız.”",
    left: { label: "Yapma, riske değmez", effects: { power: 4, sanity: -4 } },
    right: { label: "Yap, dene", effects: { power: -14, signal: -6 } },
  },
  {
    id: "entity_bargain",
    phase: 3,
    image: "images/fisilti.jpg",
    speaker: CAST.fisilti,
    text: "“Sana bir teklifim var: geri kalanının ne kadar acı çekmeden geçmesini istersen, bana antenini ver.”",
    glitchText: "“Sana bir t&klifim v&r: ac% çekmeden geçmesini... anteni ver. anteni v&r. anteni—”",
    left: { label: "Hayır, asla", effects: { signal: -16, sanity: 6 } },
    right: { label: "Dinliyorum, devam et", effects: { signal: 20, sanity: -10 } },
  },
  {
    id: "selin_final_stand",
    phase: 3,
    image: "images/selin.jpg",
    speaker: "Selin (Sığınak-12)",
    text: "“Sığınağı savunmaya karar verdik. Taktik önerin var mı, yoksa çok mu geç?”",
    left: { label: "Çok geç, kaçın", effects: { trust: -8, sanity: 4 } },
    right: { label: "Savunma planı öner", effects: { trust: 14, sanity: -6 } },
  },
  {
    id: "mirror_frequency",
    phase: 3,
    image: "images/station_cabin.jpg",
    speaker: "İstasyon — verici",
    text: "Şef'in kasetindeki gibi frekansı tersine çevirirsen ne olacağını merak ediyorsun.",
    left: { label: "Deneme, riskli", effects: { sanity: 6 } },
    right: { label: "Tersine çevir, dene", effects: { signal: 18, sanity: -10 } },
  },
  {
    id: "survivor_farewell",
    phase: 3,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — bir hayatta kalan",
    text: "“Sana teşekkür etmek için aradım sadece. Ne olursa olsun, iyi ki vardın.”",
    left: { label: "Sağ ol, dikkatli ol", effects: { trust: 8, sanity: 4 } },
    right: { label: "Asıl sen sağ ol, umarım tekrar duyuşuruz", effects: { trust: 6, sanity: 6 } },
  },
  {
    id: "countdown_to_completion",
    phase: 3,
    image: "images/fisilti.jpg",
    speaker: CAST.fisilti,
    text: "“Neredeyse tamamlandı. Sen de hissediyorsun değil mi, ne kadar yakın olduğumuzu?”",
    glitchText: "“N&redeyse ta%amlandı. N&redeyse ta%amlandı. N&r&d&yse ta%a—”",
    left: { label: "Hiçbir şey hissetmiyorum, yalan söylüyorsun", effects: { signal: -10, sanity: 4 } },
    right: { label: "Evet... hissediyorum", effects: { signal: 16, sanity: -12 } },
  },
  {
    id: "defector_unit_search",
    phase: 3,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — askeri bir ses",
    text: "“Serkan adında bir kaçağı arıyoruz, sinyalinizde olabileceğini düşünüyoruz. Gördünüz mü?”",
    left: { label: "Hayır, görmedim", effects: { trust: -4, power: 4, rel: { serkan: 15, military: -10 } } },
    right: { label: "Evet burada, gelin alın", effects: { trust: -14, power: 8, rel: { serkan: -40, military: 20 } } },
  },
  {
    id: "final_supply_run",
    phase: 3,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — bir grup gönüllü",
    text: "“Son bir tedarik seferi yapabiliriz ama çok riskli. Onaylıyor musun?”",
    left: { label: "Hayır, kimseyi riske atma", effects: { trust: 6, power: -4 } },
    right: { label: "Onayla, deneyin", effects: { power: 14, trust: -6 } },
  },
  {
    id: "choice_of_silence",
    phase: 3,
    image: "images/station_cabin.jpg",
    speaker: "İstasyon — verici anahtarı",
    text: "Elini vericinin anahtarına koyuyorsun. Tek bir hareketle her şeyi susturabilirsin.",
    glitchText: "?li%i vericinin ?nahtar%na koyuyor#un. T&k bir har&ketle he& ş&yi susturabilir#in.",
    left: { label: "Elini çek, susturma", effects: { signal: 2 } },
    right: { label: "Kapat, her şeyi sustur", effects: { signal: -30, trust: -10 } },
  },
  {
    id: "recording_for_future",
    phase: 3,
    image: "images/archive_tape.jpg",
    speaker: "İstasyon — boş bant",
    text: "Gelecekteki operatöre bir mesaj bırakabilirsin, tıpkı senden öncekinin yaptığı gibi.",
    left: { label: "Bırakma, anlamı yok", effects: { sanity: 4 } },
    right: { label: "Bir mesaj kaydet", effects: { sanity: -4, signal: 4 } },
  },
  {
    id: "ceylan_confronts_you",
    phase: 3,
    image: "images/ceylan.jpg",
    speaker: CAST.ceylan,
    text: "“Değiştin. Sesin bile değişti. Bunu görüyor musun?”",
    left: { label: "Hayır, hâlâ ben buradayım", effects: { trust: 4, sanity: -6 } },
    right: { label: "Belki haklısın", effects: { trust: -8, sanity: 8 } },
  },
  {
    id: "selin_secret_request",
    phase: 3,
    image: "images/selin.jpg",
    speaker: "Selin (Sığınak-12)",
    text: "“Sana bir sır vereceğim ama kimseye söylemeyeceğine söz ver.”",
    left: { label: "Söz veremem, dürüst olmalıyım", effects: { trust: -6, rel: { selin: -10 } } },
    right: { label: "Söz veriyorum", effects: { trust: 10, sanity: -4, rel: { selin: 10 } } },
  },
  {
    id: "serkan_last_delivery",
    phase: 3,
    image: "images/serkan.jpg",
    speaker: CAST.serkan,
    text: "“Sana son bir paket getiriyorum ama peşimde biri var, tuzak olabilir.”",
    left: { label: "Getirme, çok riskli", effects: { power: 4, trust: -4 } },
    right: { label: "Getir, riski göze al", effects: { power: 10, trust: 6, sanity: -4 } },
  },
  {
    id: "voice_grows_tired",
    phase: 3,
    image: "images/fisilti.jpg",
    speaker: CAST.fisilti,
    text: "“Bilmiyorsun ama... ben de yoruluyorum. Bu kadar uzun süre burada olmak, senin için de benim için de kolay değil.”",
    glitchText: "“B&lmiyorsun ama... b&n de yoru%uyorum... b&n de... b&n de yoru%uyo—”",
    left: { label: "Sana acımıyorum", effects: { signal: -10, sanity: 6 } },
    right: { label: "Anlıyorum seni", effects: { signal: 14, sanity: -8 } },
  },
  {
    id: "final_countdown_call",
    phase: 3,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — onlarca ses birlikte",
    text: "“Hep birlikte geri sayım yapıyoruz sanki: on, dokuz, sekiz... Sen de say bizimle.”",
    left: { label: "Hayır, susturun bunu", effects: { sanity: 6, signal: -8 } },
    right: { label: "Sen de say", effects: { sanity: -10, signal: 14 } },
  },
  {
    id: "epilogue_hint",
    phase: 3,
    image: "images/archive_tape.jpg",
    speaker: "İstasyon — raf, yeni bir not",
    text: "Rafın altında yeni bir not buluyorsun, kendi el yazınla: bunu daha önce hiç yazmadın.",
    left: { label: "Notu yok et", effects: { sanity: 6, signal: -6 } },
    right: { label: "Notu sakla, oku", effects: { sanity: -8, signal: 10 } },
  },
  {
    id: "last_generator_choice",
    phase: 3,
    image: "images/station_cabin.jpg",
    speaker: "İstasyon — jeneratör",
    text: "Jeneratörde son bir miktar yakıt kaldı. Şimdi mi harca, yoksa sonrası için mi sakla?",
    left: { label: "Sakla", effects: { power: 6 } },
    right: { label: "Şimdi harca, tam güç yayın yap", effects: { power: -16, trust: 10 } },
  },
  {
    id: "final_message_to_kayra",
    phase: 3,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — tanımadık, sakin bir ses",
    text: "“Ali Kayra... bu ismi biliyorum. Önceki banttan mı, yoksa başka bir yerden mi hatırlıyorum bilmiyorum.”",
    left: { label: "Yanlış numara, kapat", effects: { sanity: 4, signal: -4 } },
    right: { label: "Nereden biliyorsun diye sor", effects: { sanity: -8, signal: 10 } },
  },
  {
    id: "serkan_redemption",
    phase: 3,
    image: "images/serkan.jpg",
    speaker: CAST.serkan,
    text: "“Belki de tek doğru şeyi şimdi yapabilirim. Bana bir görev ver, önemli olsun.”",
    left: { label: "Sana görev vermek istemiyorum, güvenli kal", effects: { trust: 6 } },
    right: { label: "Ona zor ama anlamlı bir görev ver", effects: { trust: 12, power: -8 } },
  },
  {
    id: "ceylan_goodbye_gift",
    phase: 3,
    image: "images/ceylan.jpg",
    speaker: CAST.ceylan,
    text: "“Sana bir şey bıraktım, konsolun altında. Umarım işine yarar. Ben biraz dinleneceğim.”",
    left: { label: "Şimdi bakma, sonra", effects: { sanity: 2 } },
    right: { label: "Hemen bak", effects: { power: 8, sanity: 4 } },
  },
  {
    id: "twin_signal_3",
    phase: 3,
    hidden: true,
    image: "images/fisilti.jpg",
    speaker: "Gözcü-3 — ya da onun sesiyle konuşan başka biri",
    text: "“Gözcü-3 diye bir şey yok” diyor bir başka ses aynı frekansta. “Hiç olmadı. Sen kendi yankınla konuşuyordun.”",
    glitchText: "“G&zc&-3 diye bir ş&y y%k” diyor... yok diyor... y%k diy&r—",
    left: { label: "İnanma, gerçekti o", effects: { sanity: -10, signal: 10 } },
    right: { label: "Belki haklı, hiç var olmadı", effects: { sanity: 8, signal: -12 } },
  },

  // ============================================================
  // İÇERİK PAKETİ 3 — Gecikmeli geri bildirim kartları (24 kart)
  // Bu kartlar rastgele gelmez; sadece yukarıdaki 12 kararın
  // scheduleCallback'i tetiklendiğinde birkaç kart sonra açılır.
  // ============================================================
  {
    id: "road_survivors_valley_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — aynı grup, biraz önce",
    text: "“Vadiden geçtik, dediğin gibi. Az kalsın bir yağmacı grubuna yakalanıyorduk ama atlattık. Sağ ol.”",
    left: { label: "Rica ederim, dikkatli olun", effects: { trust: 2 } },
    right: { label: "Şanslıymışsınız", effects: { sanity: 2 } },
  },
  {
    id: "road_survivors_hill_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — aynı grup",
    text: "“Tepeden geçtik, dediğin gibi güvenliydi ama çok uzun sürdü. Biri soğuktan hastalandı.”",
    left: { label: "Geçmiş olsun, dinlensin", effects: { trust: 4 } },
    right: { label: "Güvenli olan daha önemliydi", effects: { sanity: 2 } },
  },
  {
    id: "river_avoided_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — nehirdeki adam",
    text: "“Nehri geçmedik, uzun yoldan dolandık. İki gün kaybettik ama güvendeyiz.”",
    left: { label: "Doğru karardı", effects: { trust: 4 } },
    right: { label: "Vaktinizi aldım, üzgünüm", effects: { sanity: 2 } },
  },
  {
    id: "river_crossed_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — nehirdeki adam",
    text: "“Buz kırıldı ama son anda kurtulduk. Üstüm sırılsıklam ama karşıdayım.”",
    left: { label: "Tanrıya şükret", effects: { trust: 4 } },
    right: { label: "Bir daha risk alma", effects: { sanity: 4 } },
  },
  {
    id: "medicine_focused_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — aynı grup",
    text: "“En hasta olan iyileşti ama diğerleri hâlâ kötü durumda. Bazıları seni suçluyor.”",
    left: { label: "Elimden geleni yaptım", effects: { sanity: 2 } },
    right: { label: "Üzgünüm, keşke daha fazla ilaç olsaydı", effects: { trust: 2 } },
  },
  {
    id: "medicine_shared_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — aynı grup",
    text: "“Kimse tam iyileşmedi ama kimse de ölmedi. Orta yolu bulduk, sağ ol.”",
    left: { label: "İyi ki idare ettiniz", effects: { trust: 2 } },
    right: { label: "Zor bir karardı, biliyorum", effects: { sanity: 2 } },
  },
  {
    id: "convoy_unknown_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — konvoy lideri",
    text: "“Kendi başımıza yol bulmak zorunda kaldık, iki araç kaybettik ama ilerliyoruz.”",
    left: { label: "Üzgünüm, elimde bilgi yoktu", effects: { sanity: 2 } },
    right: { label: "Bir dahakine yardımcı olurum", effects: { trust: 2 } },
  },
  {
    id: "convoy_guided_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — konvoy lideri",
    text: "“Gösterdiğin yoldan geçtik, sorunsuz ulaştık. Bir daha ararız, sağ ol.”",
    left: { label: "Ne zaman isterseniz", effects: { trust: 2 } },
    right: { label: "Dikkatli sürün", effects: { sanity: 2 } },
  },
  {
    id: "weather_silent_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — çiftçi",
    text: "“Hayvanları içeri almadık, tahminsiz kaldık. İkisini kaybettik.”",
    left: { label: "Üzgünüm, bilseydim söylerdim", effects: { sanity: 2 } },
    right: { label: "Bir dahakine daha dikkatli olurum", effects: { trust: 2 } },
  },
  {
    id: "weather_shared_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — çiftçi",
    text: "“Tahminin doğru çıktı, hayvanları zamanında topladık. Sağ ol.”",
    left: { label: "Ne demek, iyi ki işe yaradı", effects: { trust: 2 } },
    right: { label: "Şanslıydık aslında", effects: { sanity: 2 } },
  },
  {
    id: "panel_stolen_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — telaşlı bir ses",
    text: "“Paneli çaldılar. Artık elektriğimiz yok. Neden yardım etmedin?”",
    left: { label: "Üzgünüm, elimden bir şey gelmezdi", effects: { sanity: -2 } },
    right: { label: "Haklısın, keşke daha erken müdahale etseydim", effects: { trust: 2, sanity: -2 } },
  },
  {
    id: "panel_defended_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — telaşlı bir ses",
    text: "“Paneli geri aldık, biraz arbede oldu ama kazandık. Sağ ol, sözlerin bize güç verdi.”",
    left: { label: "İyi ki başardınız", effects: { trust: 2 } },
    right: { label: "Kimse yaralanmadı umarım", effects: { sanity: 2 } },
  },
  {
    id: "frostbite_untreated_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — aynı ses, daha zayıf",
    text: "“İki parmağımı kaybettim ama hayattayım. Keşke daha erken bir şey söyleseydin.”",
    left: { label: "Üzgünüm, bilgim yoktu", effects: { sanity: -2 } },
    right: { label: "Geçmiş olsun, dayan", effects: { trust: 2 } },
  },
  {
    id: "frostbite_treated_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — aynı ses",
    text: "“Anlattığın yöntem işe yaradı, parmaklarım kurtuldu. Sana çok şey borçluyum.”",
    left: { label: "Ne demek, iyi ki işe yaradı", effects: { trust: 2 } },
    right: { label: "Kendine iyi bak", effects: { sanity: 2 } },
  },
  {
    id: "dog_not_found_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — aynı kadın",
    text: "“Köpeğimi hâlâ bulamadım ama aramaya devam ediyorum. Teşekkürler yine de, umut verdin.”",
    left: { label: "Bulacağına eminim", effects: { sanity: 2 } },
    right: { label: "Aramaya devam et, pes etme", effects: { trust: 2 } },
  },
  {
    id: "dog_found_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — aynı kadın, sevinçli",
    text: "“Köpeğimi buldum! İyiymiş, sadece korkmuş. Sağ ol ki umut verdin bana.”",
    left: { label: "Çok sevindim senin adına", effects: { sanity: 4 } },
    right: { label: "Bir dahakine daha dikkatli olun", effects: { trust: 2 } },
  },
  {
    id: "caravan_unguided_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — tüccar",
    text: "“Kervan yanlış yola sapmış, birkaç günlük gecikme yaşadık. Yardımcı olmadığın için biraz kırgınız.”",
    left: { label: "Üzgünüm, sizi tanımıyordum", effects: { sanity: -2 } },
    right: { label: "Bir dahakine yardımcı olurum", effects: { trust: 2 } },
  },
  {
    id: "caravan_guided_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — tüccar",
    text: "“Önerdiğin durakta güvenle mola verdik. Teşekkürler, sana bir hediye bıraktık.”",
    left: { label: "Sağ olun, iyi yolculuklar", effects: { trust: 2 } },
    right: { label: "Hediyeye gerek yoktu ama sağ olun", effects: { power: 2 } },
  },
  {
    id: "shelter_near_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — aynı aile",
    text: "“Ulaştık ama sığınak hasarlıydı, geceyi zor geçirdik. Yine de sağ ol.”",
    left: { label: "Geçmiş olsun", effects: { trust: 2 } },
    right: { label: "Bir dahakine daha iyisini bulurum", effects: { sanity: 2 } },
  },
  {
    id: "shelter_far_result",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — aynı aile",
    text: "“Uzun sürdü ama güvenli sığınağa ulaştık. İyiyiz, teşekkürler.”",
    left: { label: "Ne demek, iyi ki iyisiniz", effects: { trust: 2 } },
    right: { label: "Dikkatli olmak her zaman kazandırır", effects: { sanity: 2 } },
  },
  {
    id: "dispute_unfair_result",
    phase: 2,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — ikinci grup",
    text: "“İlk gelen grup bizi kovdu. Şimdi başka bir yer arıyoruz. Sana artık güvenmiyoruz.”",
    left: { label: "Üzgünüm, adil olmadı biliyorum", effects: { sanity: -2 } },
    right: { label: "Size başka bir yer önereyim", effects: { trust: 2, power: -2 } },
  },
  {
    id: "dispute_fair_result",
    phase: 2,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — her iki grup",
    text: "“Bölüşüm zor oldu ama ikisi de kabul etti. Şimdilik barış var, sağ ol.”",
    left: { label: "İyi ki anlaştınız", effects: { trust: 2 } },
    right: { label: "Sorun çıkarsa yine ararım ben de", effects: { sanity: 2 } },
  },
  {
    id: "rescue_refused_result",
    phase: 2,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "İstasyon — sessiz hat",
    text: "“Askeri kurtarma ekibi” bir daha aramadı. İyi ki koordinatı vermedin, sahteydi galiba.",
    left: { label: "İçgüdülerime güvendim, iyi ki", effects: { sanity: 2 } },
    right: { label: "Kim olduklarını merak ediyorum yine de", effects: { signal: 2 } },
  },
  {
    id: "rescue_trap_result",
    phase: 2,
    hidden: true,
    image: "images/station_cabin.jpg",
    speaker: "İstasyon — konsol",
    text: "Koordinatı verdiğin yerde kimse yoktu, sadece boş bir kamp. Ya da birileri oradaydı ve gitti.",
    left: { label: "Bir daha koordinat vermem", effects: { sanity: 2 } },
    right: { label: "Onları bulmaya çalış", effects: { sanity: -6, signal: 6 } },
  },

  // ============================================================
  // İÇERİK PAKETİ 3 — Kıyamet öncesi hatıralar (6 kart)
  // ============================================================
  {
    id: "flashback_before_1",
    phase: 1,
    image: "images/ali_kayra.jpg",
    speaker: "Hatıra — Büyük Sessizlik'ten Önce",
    text: "Gözlerini kapatınca hâlâ eski hayatını görüyorsun: kalabalık bir şehir, bitmeyen bir trafik gürültüsü. Şimdi tek duyduğun rüzgâr.",
    left: { label: "Hatırlamamaya çalış", effects: { sanity: 4 } },
    right: { label: "Biraz daha hatırla", effects: { sanity: -4, signal: 2 } },
  },
  {
    id: "flashback_before_2",
    phase: 1,
    image: "images/ali_kayra.jpg",
    speaker: "Hatıra — İlk Gece",
    text: "İlk gece gökyüzü yanlış renkteydi. Herkes bunun bir fırtına olduğunu söylemişti. Radyoyu o gece ilk kez bu yüzden açmıştın.",
    left: { label: "O geceyi düşünme", effects: { sanity: 4 } },
    right: { label: "O geceyi tekrar yaşa", effects: { sanity: -6, signal: 4 } },
  },
  {
    id: "flashback_first_broadcast",
    phase: 2,
    image: "images/ali_kayra.jpg",
    speaker: "Hatıra — İlk Yayın",
    text: "İlk yayınını yaptığında sesin titriyordu. “Beni duyan var mı?” demiştin. Kimse cevap vermemişti. Ta ki üç gün sonrasına kadar.",
    left: { label: "Gurur duy, o günden beri ilerledin", effects: { sanity: 4, trust: 2 } },
    right: { label: "O günkü çaresizliği hatırla", effects: { sanity: -4 } },
  },
  {
    id: "flashback_family_1",
    phase: 1,
    image: "images/ali_kayra.jpg",
    speaker: "Hatıra — Ayrılık",
    text: "Kardeşin son kez aradığında sinyal tam da “nerede olduğunu söyle” derken kesildi. O günden beri onu bulamadın.",
    left: {
      label: "Onu düşünmemeye çalış",
      effects: { sanity: 4 },
      scheduleCallback: { id: "flashback_family_2", after: 5 },
    },
    right: {
      label: "Aramaya devam et, umudu bırakma",
      effects: { sanity: -4, trust: 2 },
      scheduleCallback: { id: "flashback_family_2", after: 5 },
    },
  },
  {
    id: "flashback_family_2",
    phase: 2,
    hidden: true,
    image: "images/fisilti.jpg",
    speaker: "Hatıra — ya da Statik",
    text: "Tanıdık bir ses diyor telsizden “Seni duyuyorum” — kardeşinin sesine çok benziyor. Ama emin olamıyorsun.",
    left: { label: "O değil, kendine söyle", effects: { sanity: 6, signal: -6 } },
    right: { label: "“Sen misin?” diye sor", effects: { sanity: -10, signal: 12 } },
  },

  // ============================================================
  // Zincir F — Serkan Güven Sınavı (A → B → C, ilişki bazlı 3 farklı final)
  // Adım A ve B'nin HER İKİ seçimi de zinciri devam ettirir; sadece
  // state.relationships.serkan'a farklı yönde etki eder. Final (C), B'nin
  // scheduleCallback'i devreye girdiği ANDAKİ serkan skoruna göre üç ayrı
  // karttan (yüksek/orta/düşük güven) birini gösterir.
  // ============================================================
  {
    id: "serkan_trust_test_A",
    phase: 2,
    image: "images/serkan.jpg",
    speaker: CAST.serkan,
    text: "“Sana bir şey emanet edeceğim ama önce güvenip güvenemeyeceğimi bilmem lazım. Karşılığında bir şey istemeden yardım eder misin?”",
    left: {
      label: "Hayır, karşılıksız yardım riskli",
      effects: { trust: -4, rel: { serkan: -15 } },
      scheduleCallback: { id: "serkan_trust_test_B", after: 3 },
    },
    right: {
      label: "Evet, karşılık beklemeden yardım ederim",
      effects: { trust: 6, rel: { serkan: 15 } },
      scheduleCallback: { id: "serkan_trust_test_B", after: 3 },
    },
  },
  {
    id: "serkan_trust_test_B",
    phase: 2,
    hidden: true,
    image: "images/serkan.jpg",
    speaker: CAST.serkan,
    text: "“Emanet ettiğim şey hakkında biri soru sordu. Ona söylemedim ama söylesem miydim, sence?”",
    left: {
      label: "Sıkı tut, kimseye söyleme",
      effects: { sanity: -2, rel: { serkan: 10 } },
      scheduleCallback: {
        id: "serkan_trust_final_mid",
        after: 5,
        relKey: "serkan",
        variants: [
          { min: 65, id: "serkan_trust_final_high" },
          { min: 30, id: "serkan_trust_final_mid" },
          { min: 0, id: "serkan_trust_final_low" },
        ],
      },
    },
    right: {
      label: "Söylesen daha iyi olurdu belki",
      effects: { trust: 4, rel: { serkan: -10 } },
      scheduleCallback: {
        id: "serkan_trust_final_mid",
        after: 5,
        relKey: "serkan",
        variants: [
          { min: 65, id: "serkan_trust_final_high" },
          { min: 30, id: "serkan_trust_final_mid" },
          { min: 0, id: "serkan_trust_final_low" },
        ],
      },
    },
  },
  {
    id: "serkan_trust_final_high",
    phase: 3,
    hidden: true,
    image: "images/serkan.jpg",
    speaker: CAST.serkan,
    text: "“Sana gerçekten güveniyorum artık. Elimdeki son mazot bidonunu ve tabancamı bırakıyorum — bana değil, sana lazım olacak.”",
    left: { label: "Kabul et, teşekkür et", effects: { power: 16, trust: 6, rel: { serkan: 10 } } },
    right: { label: "Fazla, alamam", effects: { trust: 10, rel: { serkan: 6 } } },
  },
  {
    id: "serkan_trust_final_mid",
    phase: 3,
    hidden: true,
    image: "images/serkan.jpg",
    speaker: CAST.serkan,
    text: "“Sana hâlâ temkinliyim ama düşman da değilim. Bildiklerimizi paylaşmaya devam edelim, yeter.”",
    left: { label: "Kabul, temkinli kalalım", effects: { trust: 4 } },
    right: { label: "Daha fazla güven inşa etmeye çalış", effects: { trust: 2, rel: { serkan: 6 } } },
  },
  {
    id: "serkan_trust_final_low",
    phase: 3,
    hidden: true,
    image: "images/serkan.jpg",
    speaker: "Telsiz — tanımadık askeri bir ses",
    text: "“Serkan seni ihbar etti, istasyonunun konumunu bize verdi. Karşılığında dokunulmazlık istedi.”",
    left: { label: "İnanma, tuzak olabilir", effects: { trust: -6, sanity: 4 } },
    right: { label: "İstasyonu güçlendir, savunmaya geç", effects: { power: -10, trust: 10, sanity: -6 } },
  },

  // ============================================================
  // İnteraktif Telsiz Frekans Arama (Tuner Mini-Oyunu)
  // type:"radio_tune" kartları normal sol/sağ yerine game.js'teki tuner
  // motorunu açar. targetFreq bulunup 1.2sn kilitlenince successCardId,
  // Akıl kritik seviyeye inerse failureCardId gösterilir.
  // ============================================================
  {
    id: "c_sos_transmission",
    type: "radio_tune",
    phase: 1,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — çok zayıf bir SOS",
    text: "Zayıf, kesik kesik bir SOS sinyali yakalıyorsun. Netleştirmek için tam frekansı bulman lazım.",
    targetFreq: 96.4,
    successCardId: "sos_transmission_success",
    failureCardId: "sos_transmission_failure",
  },
  {
    id: "sos_transmission_success",
    phase: 1,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — SOS'u gönderen kadın",
    text: "“Beni buldun! Adım Derya, çökmüş bir madencilik kampındayım. Yardım çağırabilir misin?”",
    left: { label: "Konumunu not al, birini yönlendir", effects: { trust: 12, power: -4 } },
    right: { label: "Yalnız değilsin de, dayan", effects: { trust: 6, sanity: 4 } },
  },
  {
    id: "sos_transmission_failure",
    phase: 1,
    hidden: true,
    image: "images/station_cabin.jpg",
    speaker: "İstasyon — statik",
    text: "Sinyal tam bulunacakken bir cızırtıya karışıp sonsuza dek kayboluyor. Kimin sesi olduğunu hiç öğrenemeyeceksin.",
    left: { label: "Unutmaya çalış", effects: { sanity: 4 } },
    right: { label: "Aramaya devam et, boşuna", effects: { sanity: -6, trust: -4 } },
  },

  {
    id: "c_military_chatter",
    type: "radio_tune",
    phase: 2,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — şifreli bir konuşma parçası",
    text: "Askeri bir kanal olduğunu düşündüğün şifreli bir konuşma sızıyor. Tam frekansı bulursan belki bir şey öğrenirsin.",
    targetFreq: 101.2,
    successCardId: "military_chatter_success",
    failureCardId: "military_chatter_failure",
  },
  {
    id: "military_chatter_success",
    phase: 2,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — askeri kanal",
    text: "“...konvoy B-7 hattından çekiliyor, bölge artık güvenli değil...” Bunu bilmemen gerekiyordu, ama artık biliyorsun.",
    left: {
      label: "Bilgiyi kimseyle paylaşma",
      effects: { signal: -4, rel: { military: -6 } },
      scheduleCallback: { id: "defne_first_contact", after: 3 },
    },
    right: {
      label: "Dinleyicilerini uyar",
      effects: { trust: 10, rel: { military: -12 } },
      scheduleCallback: { id: "defne_first_contact", after: 3 },
    },
  },
  {
    id: "military_chatter_failure",
    phase: 2,
    hidden: true,
    image: "images/station_cabin.jpg",
    speaker: "İstasyon — statik",
    text: "Konuşma tam anlaşılacakken parazite karışıyor. Ne öğrenecektin, artık bilemeyeceksin.",
    left: { label: "Vazgeç, boşuna uğraşma", effects: { sanity: 2 } },
    right: { label: "Sinirlen, tekrar dene", effects: { sanity: -4, power: -4 } },
  },

  {
    id: "c_entity_whisper",
    type: "radio_tune",
    phase: 3,
    image: "images/fisilti.jpg",
    speaker: "88.4 MHz — bir fısıltı, çok uzaktan",
    text: "Tanıdık bir fısıltı, ama bu kez kendi frekansında değil. Onu bulmak istiyor musun, gerçekten?",
    targetFreq: 88.4,
    successCardId: "entity_whisper_success",
    failureCardId: "entity_whisper_failure",
  },
  {
    id: "entity_whisper_success",
    phase: 3,
    hidden: true,
    image: "images/fisilti.jpg",
    speaker: CAST.fisilti,
    text: "“Beni bulman bu kadar kolay olmamalıydı. Ya da her zaman bu kadar yakınımdaydın.”",
    glitchText: "“B&ni bulman bu kadar ko%ay olmamalıydı. Y& da her z&man bu kadar yakınımd&ydın.”",
    left: { label: "Uzaklaş, korkuyla", effects: { signal: -10, sanity: -6 } },
    right: { label: "Yaklaş, dinle", effects: { signal: 18, sanity: -10 }, nextCardId: "entity_direct_address" },
  },
  {
    id: "entity_direct_address",
    phase: 3,
    hidden: true,
    image: "images/fisilti.jpg",
    speaker: CAST.fisilti,
    text: "“—dinliyorsun değil mi. Biliyorum dinliyorsun, çünkü ses seviyeni açtın az önce, tık sesini duydum. Hoş geldin. Burada kimse bağırmıyor. Burada kimse ağlamıyor. Sadece dinliyoruz. Sen de gelip dinlersen, çok daha... hafif hissedeceksin. Söz veriyorum. Söz veriyorum. Söz veriyorum.”",
    glitchText: "“—d&nliyorsun değil mi. S&z ver&yorum. S&z ver&yorum. S&z ver&yo—”",
    left: { label: "Telsizi kapat, uzaklaş", effects: { signal: -18, sanity: 10 } },
    right: { label: "...sesini biraz daha aç", effects: { signal: 14, sanity: -18 } },
  },
  {
    id: "entity_whisper_failure",
    phase: 3,
    hidden: true,
    image: "images/station_cabin.jpg",
    speaker: "İstasyon — ani bir kesinti",
    text: "Frekans bulunacakken acil durum devresi atıyor, verici bir anlığına tamamen sessizleşiyor. Belki de bulunmak istemiyordu.",
    left: { label: "Rahatladığını fark et", effects: { sanity: 6, signal: -8 } },
    right: { label: "Bunun bir işaret olduğunu düşün", effects: { sanity: -6, signal: 6 } },
  },

  // ============================================================
  // Mors Kod Çözme Mini-Oyunu — type:"morse_decode" kartları normal sol/sağ
  // yerine game.js'teki mors motorunu açar (bkz. startMorseDecode). pattern
  // bir kez çalınır; oyuncu "BAS" düğmesini kısa (nokta) / uzun (çizgi)
  // basılı tutarak aynı deseni tekrar etmeli. İlk yanlış sembolde anında
  // failureCardId'ye düşer.
  // ============================================================
  {
    id: "c_morse_silent_caller",
    type: "morse_decode",
    phase: 2,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — sessiz bir hat",
    text: "Konuşan yok ama hat da kapanmıyor. Sonra fark ediyorsun: biri, sesini çıkaramadan, tuşlara vurarak konuşmaya çalışıyor.",
    pattern: ["dot", "dash", "dot", "dot"],
    successCardId: "morse_silent_caller_success",
    failureCardId: "morse_silent_caller_failure",
  },
  {
    id: "morse_silent_caller_success",
    phase: 2,
    hidden: true,
    image: "images/radio_caller.jpg",
    speaker: "Telsiz — aynı sessiz hat",
    text: "Deseni doğru okuyorsun: “...YANIMDA... KONUŞAMIYORUM... ODADA...” Sonra hat, hiç açık kalmamış gibi, birden kesiliyor.",
    left: { label: "Konumunu tahmin etmeye çalış", effects: { sanity: -8, trust: 10 } },
    right: { label: "Sessizce dinlemeye devam et", effects: { sanity: -4, signal: 6 } },
  },
  {
    id: "morse_silent_caller_failure",
    phase: 2,
    hidden: true,
    image: "images/station_cabin.jpg",
    speaker: "İstasyon — statik",
    text: "Ritmi kaçırıyorsun. Vuruşlar birbirine karışıyor, sonra aniden duruyor — sanki karşı taraf artık vurmaya cesaret edemiyormuş gibi.",
    left: { label: "Unut, boş ver", effects: { sanity: 4, signal: -6 } },
    right: { label: "Ne demeye çalıştığını düşünüp dur", effects: { sanity: -6, signal: 4 } },
  },

  // ============================================================
  // KARAKTER GENİŞLEME PAKETİ — Eski Nöbetçi Mert Zinciri (10 kart)
  // rel.mert'e bağlı; final, güven skoruna göre 3 ayrı sonuçtan birine açılır.
  // ============================================================
  {
    id: "mert_arrival",
    phase: 1,
    image: "images/station_cabin.jpg",
    speaker: "Kapıda bir adam, donmak üzere",
    text: "“Lütfen... İçeri alın beni. Daha fazla dayanamam.” Kapıyı yumrukluyor, sesi zar zor çıkıyor.",
    left: {
      label: "Kapıyı açma, tanımıyorsun",
      effects: { trust: -8, rel: { mert: -15 } },
      scheduleCallback: { id: "mert_refused_result", after: 2 },
    },
    right: {
      label: "İçeri al",
      effects: { trust: 10, power: -4, rel: { mert: 15 } },
      scheduleCallback: { id: "mert_settling_in", after: 2 },
    },
  },
  {
    id: "mert_refused_result",
    phase: 1,
    hidden: true,
    image: "images/station_cabin.jpg",
    speaker: "İstasyon — kapının önünde, sessizlik",
    text: "Ertesi sabah kapının önünde donmuş ayak izlerinden başka bir şey yok. Kim olduğunu hiç öğrenemeyeceksin.",
    left: { label: "Unutmaya çalış", effects: { sanity: 4 } },
    right: { label: "Vicdan azabı çek", effects: { sanity: -6, trust: -4 } },
  },
  {
    id: "mert_settling_in",
    phase: 1,
    hidden: true,
    image: "images/mert.jpg",
    speaker: CAST.mert,
    text: "“Adım Mert. Eskiden bir sığınağın nöbetçisiydim, ta ki... boş ver. Ne iş yapabilirim burada, göster.”",
    left: {
      label: "Sadece dinlensin, acele etme",
      effects: { trust: 4, rel: { mert: 6 } },
      scheduleCallback: { id: "mert_night_watch_1", after: 4 },
    },
    right: {
      label: "Hemen nöbete koy",
      effects: { power: 4, sanity: -2, rel: { mert: -4 } },
      scheduleCallback: { id: "mert_night_watch_1", after: 3 },
    },
  },
  {
    id: "mert_night_watch_1",
    phase: 2,
    hidden: true,
    image: "images/mert.jpg",
    speaker: CAST.mert,
    text: "“Gece kapıya biri geldi, yağmacı gibiydi. Kovaladım ama... elim ayağım hâlâ titriyor.”",
    left: {
      label: "İyi iş çıkardın, güven ver",
      effects: { trust: 2, rel: { mert: 12 } },
      scheduleCallback: { id: "mert_night_watch_2", after: 4 },
    },
    right: {
      label: "Bir dahakine daha sert ol de",
      effects: { sanity: -2, rel: { mert: -8 } },
      scheduleCallback: { id: "mert_night_watch_2", after: 4 },
    },
  },
  {
    id: "mert_night_watch_2",
    phase: 2,
    hidden: true,
    image: "images/mert.jpg",
    speaker: CAST.mert,
    text: "“Bu sefer insan değildi kapıya gelen. Ya da öyle olduğunu sanmıyorum. Ama gitmesini sağladım.”",
    left: {
      label: "Ne demek istediğini sorma",
      effects: { sanity: 4 },
      scheduleCallback: { id: "mert_paranoia_signs", after: 4 },
    },
    right: {
      label: "Detay iste, ciddiye al",
      effects: { sanity: -6, signal: 4, rel: { mert: 8 } },
      scheduleCallback: { id: "mert_paranoia_signs", after: 4 },
    },
  },
  {
    id: "mert_paranoia_signs",
    phase: 2,
    hidden: true,
    image: "images/mert.jpg",
    speaker: CAST.mert,
    text: "Artık uyumuyor sanki. Sürekli kapıyı kontrol ediyor, kendi kendine konuşuyor: “Geliyorlar, geliyorlar...”",
    left: {
      label: "Onunla konuş, sakinleştirmeye çalış",
      effects: { sanity: -4, rel: { mert: 10 } },
      scheduleCallback: { id: "mert_whistling_tune", after: 3 },
    },
    right: {
      label: "Mesafeni koru, izle",
      effects: { rel: { mert: -6 } },
      scheduleCallback: { id: "mert_whistling_tune", after: 3 },
    },
  },
  {
    id: "mert_whistling_tune",
    phase: 2,
    hidden: true,
    image: "images/mert.jpg",
    speaker: CAST.mert,
    text: "“Nöbetteyken bir şey fark ettim de sana söylemeden duramadım: eskiden gece nöbetlerinde kendi kendime ıslık çalardım, biliyorsun. Bu gece fark ettim ki üç gündür aynı melodiyi çalıyormuşum. Hangi şarkı olduğunu hatırlamıyorum. Ama çok huzur verici, Ali. Sen de duymalısın.”",
    left: {
      label: "Islık çalmayı kes, ona söyle",
      effects: { sanity: 4, rel: { mert: -8 } },
      scheduleCallback: { id: "mert_final_test", after: 3 },
    },
    right: {
      label: "Zararsız bir alışkanlık, boş ver",
      effects: { sanity: -8, rel: { mert: 6 } },
      scheduleCallback: { id: "mert_final_test", after: 3 },
    },
  },
  {
    id: "mert_final_test",
    phase: 3,
    hidden: true,
    image: "images/mert.jpg",
    speaker: CAST.mert,
    text: "Elinde cephane sandığının anahtarı var. Sana bakıyor, bir şey söylemeye çalışıyor ama söyleyemiyor.",
    left: {
      label: "Anahtarı iste geri",
      effects: { sanity: -4 },
      scheduleCallback: {
        id: "mert_finale_flee",
        after: 2,
        relKey: "mert",
        variants: [
          { min: 65, id: "mert_finale_resolved" },
          { min: 30, id: "mert_finale_flee" },
          { min: 0, id: "mert_finale_hostage" },
        ],
      },
    },
    right: {
      label: "Ona güvendiğini göster, bırak",
      effects: { sanity: -2, rel: { mert: 10 } },
      scheduleCallback: {
        id: "mert_finale_flee",
        after: 2,
        relKey: "mert",
        variants: [
          { min: 65, id: "mert_finale_resolved" },
          { min: 30, id: "mert_finale_flee" },
          { min: 0, id: "mert_finale_hostage" },
        ],
      },
    },
  },
  {
    id: "mert_finale_resolved",
    phase: 3,
    hidden: true,
    image: "images/mert.jpg",
    speaker: CAST.mert,
    text: "“Gitmeyi düşündüm ama gidemedim. Buradayım, seninle. Sonuna kadar.” Cephane sandığını sana geri veriyor.",
    left: { label: "Teşekkür et", effects: { trust: 10, sanity: 6 } },
    right: { label: "Onu resmî nöbetçi yap", effects: { power: 6, trust: 8, rel: { mert: 8 } } },
  },
  {
    id: "mert_finale_flee",
    phase: 3,
    hidden: true,
    image: "images/station_cabin.jpg",
    speaker: "İstasyon — boş bir köşe",
    text: "Mert'i bulamıyorsun. Cephane sandığının yarısı da onunla birlikte gitmiş. Bir not bırakmış: “Üzgünüm. Daha fazla dayanamadım.”",
    left: { label: "Peşinden gitme, bırak", effects: { power: -10, sanity: -4 } },
    right: { label: "Onu bulmaya çalış", effects: { power: -6, sanity: -8, trust: -4 } },
  },
  {
    id: "mert_finale_hostage",
    phase: 3,
    hidden: true,
    image: "images/mert.jpg",
    speaker: CAST.mert,
    text: "Elinde silahla konsolun başında duruyor. “Kimse çıkmıyor, kimse girmiyor, ta ki bana gerçeği söyleyene kadar!”",
    left: { label: "Sakinleştirmeye çalış, konuş", effects: { sanity: -10, trust: -6 } },
    right: { label: "Karşı çık, riske gir", effects: { power: -8, sanity: -14, trust: -10 } },
  },

  // ============================================================
  // KARAKTER GENİŞLEME PAKETİ — Korsan Telsizci Buse Zinciri (10 kart)
  // rel.defne'ye bağlı; sadece bir Tuner başarısından sonra tetiklenir
  // (bkz. military_chatter_success), final rel.defne skoruna göre 3 sonuçtan biri.
  // ============================================================
  {
    id: "defne_first_contact",
    phase: 2,
    hidden: true,
    image: "images/buse.jpg",
    speaker: CAST.defne,
    text: "“Sinyalini yakaladım, senden çok uzakta değilim. Bana Buse diyebilirsin. Birkaç şifreli koordinat ister misin?”",
    left: { label: "Reddet, tanımıyorsun", effects: { signal: -4, rel: { defne: -10 } } },
    right: {
      label: "Dinle, ne diyor bakalım",
      effects: { signal: 8, rel: { defne: 10 } },
      scheduleCallback: { id: "defne_first_offer", after: 3 },
    },
  },
  {
    id: "defne_first_offer",
    phase: 2,
    hidden: true,
    image: "images/buse.jpg",
    speaker: CAST.defne,
    text: "“Anteni şu şekilde ayarlarsan çok daha net şeyler duyarsın. Küçük bir ayar, söz veriyorum.”",
    left: {
      label: "Riske değmez, reddet",
      effects: { signal: -4, rel: { defne: -8 } },
      scheduleCallback: { id: "defne_isolation_crack", after: 4 },
    },
    right: {
      label: "Dene",
      effects: { signal: 12, sanity: -8, rel: { defne: 12 } },
      scheduleCallback: { id: "defne_isolation_crack", after: 3 },
    },
  },
  {
    id: "defne_isolation_crack",
    phase: 2,
    hidden: true,
    image: "images/station_cabin.jpg",
    speaker: "İstasyon — duvarlar",
    text: "Duvarlardan tuhaf bir uğultu geliyor artık, hiç olmadığı kadar net. Buse rahatlatmaya çalışıyor: “Normal, alışırsın.”",
    left: {
      label: "Kayıtsız kal",
      effects: { sanity: -4 },
      scheduleCallback: { id: "defne_second_offer", after: 4 },
    },
    right: {
      label: "Buse'ye güven, devam et",
      effects: { sanity: -6, signal: 6, rel: { defne: 8 } },
      scheduleCallback: { id: "defne_second_offer", after: 3 },
    },
  },
  {
    id: "defne_second_offer",
    phase: 3,
    hidden: true,
    image: "images/buse.jpg",
    speaker: CAST.defne,
    text: "“Sana bir frekans daha göstereceğim ama bu sefer yalıtımın bir kısmını sökmen gerekiyor. Karşılığında askerlerin hareketlerini gösterebilirim.”",
    left: {
      label: "Yalıtımı sökme, çok riskli",
      effects: { sanity: 4, rel: { defne: -12 } },
      scheduleCallback: { id: "defne_paranoia_beat", after: 4 },
    },
    right: {
      label: "Sök, göster bana",
      effects: { sanity: -12, signal: 14, rel: { defne: 14, military: -5 } },
      scheduleCallback: { id: "defne_paranoia_beat", after: 3 },
    },
  },
  {
    id: "defne_paranoia_beat",
    phase: 3,
    hidden: true,
    image: "images/buse.jpg",
    speaker: CAST.defne,
    text: "Artık onun sesiyle statiğin arasındaki farkı ayırt edemiyorsun bazen. O da fark ediyor: “Yorgun görünüyorsun.”",
    glitchText: "“Y&rgun g&r&n&yorsun&” d&yor. S&sü st&tikle kar%ı%ıyor. H&ngisi &, h&ngisi s&n, artık b&lemiyorsun.",
    left: {
      label: "Uzaklaş, ara ver",
      effects: { sanity: 8, signal: -6, rel: { defne: -6 } },
      scheduleCallback: { id: "defne_window_visitor", after: 5 },
    },
    right: {
      label: "Devam etmek istiyorum",
      effects: { sanity: -6, rel: { defne: 6 } },
      scheduleCallback: { id: "defne_window_visitor", after: 4 },
    },
  },
  {
    id: "defne_window_visitor",
    phase: 3,
    hidden: true,
    image: "images/buse.jpg",
    speaker: CAST.defne,
    text: "“...biliyorum beni duyabiliyorsun, hattaki cızırtıdan belli. Sormayacağım nasıl olduğunu, iyi olmadığını zaten biliyorum. Sadece... bu gece pencereme biri geldi. Uzun süre durdu. Gitmeden önce, tam camdan uzaklaşırken, bana gülümsedi. Tanıdığım biriydi ama adını hatırlamıyorum artık. Hiç kimsenin adını hatırlamıyorum. Sen benim adımı hatırlıyor musun?”",
    left: {
      label: "Adını hatırlıyorum, Buse",
      effects: { sanity: 4, rel: { defne: 12 } },
      scheduleCallback: { id: "defne_entity_offer", after: 4 },
    },
    right: {
      label: "Cevap verme, hatları kapat",
      effects: { sanity: 6, signal: -8, rel: { defne: -10 } },
      scheduleCallback: { id: "defne_entity_offer", after: 4 },
    },
  },
  {
    id: "defne_entity_offer",
    phase: 3,
    hidden: true,
    image: "images/buse.jpg",
    speaker: CAST.defne,
    text: "“O sesi sen de duyuyorsun değil mi, 88.4'teki? Onun frekansına sızmanın bir yolunu buldum galiba. Denemek ister misin?”",
    left: {
      label: "Hayır, ondan uzak dur",
      effects: { signal: -10, rel: { defne: -15 } },
      scheduleCallback: { id: "defne_entity_attempt", after: 4 },
    },
    right: {
      label: "Nasıl yapacağını anlat",
      effects: { signal: 10, sanity: -6, rel: { defne: 15 } },
      scheduleCallback: { id: "defne_entity_attempt", after: 3 },
    },
  },
  {
    id: "defne_entity_attempt",
    phase: 3,
    hidden: true,
    image: "images/fisilti.jpg",
    speaker: CAST.defne,
    text: "“Şimdi, birlikte. Anteni benimle aynı anda çevir.” Statik bir anda kesiliyor — sonra çok daha derin bir şey başlıyor.",
    left: {
      label: "Son anda vazgeç",
      effects: { signal: -14, sanity: 6 },
      scheduleCallback: {
        id: "defne_epilogue_neutral",
        after: 2,
        relKey: "defne",
        variants: [
          { min: 65, id: "defne_epilogue_ally" },
          { min: 30, id: "defne_epilogue_neutral" },
          { min: 0, id: "defne_epilogue_rival" },
        ],
      },
    },
    right: {
      label: "Sonuna kadar git",
      effects: { signal: 22, sanity: -14, rel: { defne: 10 } },
      scheduleCallback: {
        id: "defne_epilogue_neutral",
        after: 2,
        relKey: "defne",
        variants: [
          { min: 65, id: "defne_epilogue_ally" },
          { min: 30, id: "defne_epilogue_neutral" },
          { min: 0, id: "defne_epilogue_rival" },
        ],
      },
    },
  },
  {
    id: "defne_epilogue_ally",
    phase: 3,
    hidden: true,
    image: "images/buse.jpg",
    speaker: CAST.defne,
    text: "“Sağ çıktık. İkimiz de.” Sesi ilk kez gerçekten rahatlamış geliyor. “Frekansımı hep açık tutacağım, ihtiyacın olursa.”",
    left: { label: "İyi ki yanımdaydın", effects: { trust: 8, sanity: 6, rel: { defne: 6 } } },
    right: { label: "Bir daha asla, dedin bunu kendine", effects: { sanity: 4, signal: -6 } },
  },
  {
    id: "defne_epilogue_neutral",
    phase: 3,
    hidden: true,
    image: "images/buse.jpg",
    speaker: CAST.defne,
    text: "“Sağ çıktık ama... bilmiyorum artık kimin fikriydi bu, kimin sesiydi asıl. Belki bir süre konuşmasak iyi olur.”",
    left: { label: "Haklısın, ara ver", effects: { sanity: 4, signal: -4 } },
    right: { label: "Hayır, hattı açık tut", effects: { sanity: -4, rel: { defne: 8 } } },
  },
  {
    id: "defne_epilogue_rival",
    phase: 3,
    hidden: true,
    image: "images/fisilti.jpg",
    speaker: "Telsiz — artık Buse'ye benzemeyen bir ses",
    text: "Hattın sonunda Buse yok artık, ya da hiç yoktu. Sadece senin sesini tekrar eden bir statik var.",
    left: { label: "Hattı kapat, bir daha açma", effects: { signal: -16, sanity: 8 } },
    right: { label: "Adını sormaya devam et", effects: { signal: 12, sanity: -12 } },
  },
  {
    // Gizli kanal: herhangi bir Tuner oturumunda 94.2 MHz'e kilitlenerek keşfedilir (bkz. game.js: triggerBuseSecretChannel).
    id: "defne_secret_channel",
    phase: 2,
    hidden: true,
    image: "images/buse.jpg",
    speaker: CAST.defne,
    text: "“94.2'yi buldun demek. Bunu resmi telsizde kimseye söylemiyorum. Bu benim kendi hattım — istersen sadece ikimiz arasında kalsın.”",
    left: { label: "Bu hattı unut, tehlikeli", effects: { signal: -6, rel: { defne: -8 } } },
    right: { label: "Kalsın, sadece ikimiz arasında", effects: { signal: 6, trust: 4, rel: { defne: 14 } } },
  },

  /* ---------- Hafıza Mektupları (Memory Lore Engine) ----------
     type:"memory_letter" olan kartlar swipe kullanmaz; game.js state.day eşiğine göre zorla gösterilir
     (bkz. MEMORY_LETTER_DAYS/pendingMemoryLetterId). {{...}} işaretli bölümler sansürlüdür, yalnızca
     Zihin Eşleme mini-oyunu çözülünce açılır (bkz. renderLetterText/startMemoryResonance). Dört mektup da
     çözülünce kapı şifresinin haneleri birleşir ve memory_code_complete → true_escape_ending zinciri açılır. */
  {
    id: "memory_letter_1",
    phase: 2,
    hidden: true,
    type: "memory_letter",
    image: "images/archive_tape.jpg",
    speaker: "Hafıza Parçası — Kendi El Yazın",
    text: "“{{Şubat}}'ın başıydı, radyoyu ilk kez ben açtım... Sana kim olduğumu unutturacaklarını biliyordum, bu yüzden şifreyi burada bırakıyorum, sakla: birinci hane {{4}}. Sığınak-7'nin dışında hâlâ {{nefes alan biri}} var mıydı, hatırlamıyorum.”",
  },
  {
    id: "memory_letter_2",
    phase: 3,
    hidden: true,
    type: "memory_letter",
    image: "images/archive_tape.jpg",
    speaker: "Hafıza Parçası — Kendi El Yazın",
    text: "“Askerler geldiğinde {{üç gün}} önceydi. Bana 'gönüllüsün' dediler ama ben hiçbir şeye gönüllü olmadım. Şifrenin ikinci hanesi {{7}}. Kapının arkasında {{ailem}} olabilir, olmayabilir de.”",
  },
  {
    id: "memory_letter_3",
    phase: 3,
    hidden: true,
    type: "memory_letter",
    image: "images/archive_tape.jpg",
    speaker: "Hafıza Parçası — Kendi El Yazın",
    text: "“Fısıltı bana bir isim verdi: {{Gözcü-7}}. Ama bu istasyonun asıl adı bu değildi. Üçüncü hane: {{1}}. Bir şey daha var — kapıyı ben kilitlemedim, {{onlar kilitledi, beni içeride bırakmak için}}.”",
  },
  {
    id: "memory_letter_4",
    phase: 3,
    hidden: true,
    type: "memory_letter",
    image: "images/archive_tape.jpg",
    speaker: "Hafıza Parçası — Kendi El Yazın",
    text: "“Son not, kendime: eğer bunu okuyorsan hâlâ hayattasın demektir. Dördüncü ve son hane: {{9}}. Diğer üçünü zaten biliyorsun, birleştir. {{Kapıyı aç. Dışarısı senin sandığın gibi değil ama gerçek.}} Buraya geri dönme.”",
  },
  {
    id: "memory_code_complete",
    phase: 3,
    hidden: true,
    image: "images/ali_kayra.jpg",
    speaker: "Sen",
    text: "Dört parça birleşti, kafanda net bir dizi beliriyor: 4-7-1-9. Ana kapının şifresi bu. Sığınağın en dip koridorunda, hiç açmadığın o kapı seni bekliyor.",
    left: { label: "Hemen kapıya git", effects: {}, nextCardId: "true_escape_ending" },
    right: { label: "Önce yayını bitir, sonra git", effects: { trust: 5 }, nextCardId: "true_escape_ending" },
  },
  {
    id: "true_escape_ending",
    phase: 3,
    hidden: true,
    image: "images/ali_kayra.jpg",
    speaker: "Sen",
    text: "Parmakların titriyor. 4-7-1-9. Kilit mekanizması eski ama çalışıyor — bir 'klik' sesi, sonra ağır bir gıcırtı. Kapı, ilk kez, açılıyor.",
    left: { label: "Işığa doğru yürü", effects: {}, triggerEnding: "true_escape" },
    right: { label: "Son kez telsize dön, kapat", effects: {}, triggerEnding: "true_escape" },
  },
];

/* Her oyunun başında gösterilen, senaryoyu etkilemeyen tanıtım kartı.
   Hangi yöne kaydırılırsa kaydırılsın aynı sonuca gider (bkz. game.js resolveChoice). */
function buildIntroCard(tapeNumber) {
  return {
    id: "__intro__",
    image: "images/ali_kayra.jpg",
    speaker: `SEN — ${STORY_META.operatorName}`,
    text: `${STORY_META.stationName} acil durum yayın istasyonunun son operatörüsün. Bu BANT #${String(tapeNumber).padStart(3, "0")} — hayatta kalma girişimin. Dışarısı sessiz. İçeride sadece sen ve mikrofon var.`,
    left: { label: "Derin nefes al" },
    right: { label: "Mikrofonu aç" },
  };
}

/* Sabit Giriş Zinciri: rastgele havuzdan ÖNCE, her koşuda AYNI sırayla oynanan 3 kart.
   Amaç: oyuncuyu doğrudan rastgele (ve bağlamsız gelebilen) kartların içine atmadan önce
   dünyayı ve göreve neden ihtiyaç duyulduğunu kurmak. hidden:true — rastgele havuzdan asla
   çekilmez, sadece bu zincirle (nextCardId) ulaşılır. Hangi yöne kaydırılırsa kaydırılsın
   aynı sıradaki bir sonraki karta gider; anlatı bu üç kartta dallanmaz. */
const INTRO_CHAIN_FIRST_ID = "intro_chain_1";
{
  const introChain = [
    {
      id: "intro_chain_1",
      image: "images/station_cabin.jpg",
      speaker: `SEN — ${STORY_META.operatorName}`,
      text: "Üç hafta oldu. Önce radyolardan bir uğultu sızdı, sonra televizyonlardan. Duyanlar durdu, gülümsedi, bir daha hiç eskisi gibi olmadı. Sivil Savunma buna 'Parazit Frekans' diyor. Ben buna Gözcü-7'nin neden hâlâ ayakta olduğunun cevabı diyorum: bu duvarlar, kazara, o sesi dışarıda bırakacak kadar kalın.",
      left: { label: "Kayda devam et" },
      right: { label: "Kayda devam et" },
    },
    {
      id: "intro_chain_2",
      image: "images/radio_caller.jpg",
      speaker: `SEN — ${STORY_META.operatorName}`,
      text: "Elimde resmi bir acil durum frekansı var. İnsanlar hâlâ onu tanıyor, hâlâ güveniyor — kriz başlamadan önce de oradaydı çünkü. Görevim basit: yayında kal, doğru bilgiyi ver, kimin hâlâ hayatta olduğunu öğren. Basit olan hiçbir şey burada kolay değil.",
      left: { label: "Mikrofonu aç" },
      right: { label: "Mikrofonu aç" },
    },
    {
      id: "intro_chain_3",
      image: "images/ali_kayra.jpg",
      speaker: `SEN — ${STORY_META.operatorName}`,
      text: "Tam olarak yalnız değilim. Hâlâ cevap veren birkaç ses var — kimi asker, kimi sadece korkmuş biri. Kime güveneceğimi zamanla anlayacağım. Şimdilik tek yapabileceğim dinlemek, not almak, hayatta kalmak. Bant kaydı başlıyor.",
      left: { label: "Yayına başla" },
      right: { label: "Yayına başla" },
    },
  ];
  introChain.forEach((card, i) => {
    card.hidden = true;
    if (i < introChain.length - 1) {
      const nextId = introChain[i + 1].id;
      card.left.nextCardId = nextId;
      card.right.nextCardId = nextId;
    }
    DECK.push(card);
  });
}

const PHASE_THRESHOLDS = { 1: [1, 5], 2: [6, 12], 3: [13, Infinity] };

function cardsForPhase(phase) {
  return DECK.filter((c) => c.phase === phase && !c.hidden);
}

function phaseForDay(day) {
  if (day <= PHASE_THRESHOLDS[1][1]) return 1;
  if (day <= PHASE_THRESHOLDS[2][1]) return 2;
  return 3;
}
